### ISSUE TITLE
Bug in reformatFragmentFiles()

### ISSUE THREAD

**Issue by sychen9584** [GreenleafLab/ArchR#1076]
Hi,

Currently, running reformatFragmentFiles() will end with the error 

`Error in .fileRename(paste0(fileNew, ".bgz"), paste0(fileNew, ".gz")) :                                                              
  Input file does not exist!`

I took a look at the source code and it seems that this issue is potentially caused by the original file being deleted before renaming.

https://github.com/GreenleafLab/ArchR/blob/6765ad962d4d8dcb292a326071c9b5c30c25918e/R/HelperUtils.R#L83-L85

Even though the rest of the function is working, this means that currently only one fragment file can be processed at a time with each function call.

**Comment by LornaWessels** [comment]
Hi, 

I'm getting the same error. 

For the three fragment files of the tutorial data it works fine but when I try to run it on bed.gz fragment files. It crashes with the above described error. 
After running reformatFragmentFiles() I have two files in my directory the original file.bed.gz and the new file.bed.bgz.

**Comment by rcorces** [comment]
@LornaWessels - I imagine your input files are not correctly formatted. In particular, I bet your "bed.gz" were created with gzip rather than bgzip. Fragment files are bgzipped.

**Comment by LornaWessels** [comment]
Thanks for your quick reply! 

Converting the files with `zcat file.gz | bgzip -c > file.bgz` allowed me to pass them successfully to createArrowFiles(). 
However, the above error persisted when trying to run reformatFragmentFiles() on the converted files. 

Thank you very much anyway! This helped me a lot.

**Comment by rcorces** [comment]
@LornaWessels - glad you are able to create Arrows.
If anyone else runs into this issue, I think I would need you to provide me with the fragment files so that I can recapitulate the error.

**Comment by LornaWessels** [comment]
Hi again, 

Here's a little follow-up: 
I realised the reformatFragmentFiles() function crashed for me because I provided .bed.gz and .txt.gz fragment files as input from which the *-Reformat.tsv files could not have been created because the extensions are not given when fileNew is created. 

`fileNew <- gsub(".tsv.bgz|.tsv.gz", "-Reformat.tsv", fragmentFiles[i])`

I forked your repo and opened a pull request for the branch release_1.0.2. --> https://github.com/GreenleafLab/ArchR/pull/1227

Thank you again for your help and the effort you put into ArchR!
