### ISSUE TITLE
bug in ArrowRead.R

### ISSUE THREAD

**Issue by haibol2016** [GreenleafLab/ArchR#1130]
Lines 786 and 801 in https://github.com/haibol2016/ArchR/blob/master/R/ArrowRead.R, 

`if(!all(cellNames %in% colnames(mat))) ` should be  be changed to `if(!all(colnames(mat) %in% cellNames))`

I am not sure why it is necessary to check this condition, because the random sampling is done using cellNames as the universal.

**Comment by rcorces** [comment]
You can use permalinks to point directly to specific lines of code.

I dont believe this suggestion is correct. If you look at the code:
https://github.com/haibol2016/ArchR/blob/b2a1bc5e748dc9abdc2307605042ad3530edb530/R/ArrowRead.R#L786
is inside of `if(doSampleCells)` meaning that the matrix will not consist of all cells, just a subsample.

**Comment by rcorces** [comment]
Thanks for reporting. Apologies for my previously deleted post. I got confused by your link.
In the future, you can use permalinks to point directly to specific lines in the ArchR codebase.

For ex.
https://github.com/GreenleafLab/ArchR/blob/6765ad962d4d8dcb292a326071c9b5c30c25918e/R/ArrowRead.R#L786
rather than pointing to your forked version.

I do believe this suggestion is correct. Though I think this only manifests as a bug at the line shown above (786) because the matrix has been subsampled so not all cellNames are in the colnames. So I havent changed it at line 801.

This has been patched in `release_1.0.2` via https://github.com/GreenleafLab/ArchR/commit/75544172bc1962fd0050bb190450ee826ce1aba0

Feel free to comment again here as needed.

**Comment by rcorces** [comment]
Not my best work on this. I wasnt paying attention to my branch. This suggestion has already been fixed in `release_1.0.2`:
https://github.com/GreenleafLab/ArchR/blob/b2f3d95171ea1d708ae1e39a980669091d02689f/R/ArrowRead.R#L792

I inadvertently was looking at master so I reverted that previous change.
