### ISSUE TITLE
highlighting cells with plotEmbedding() 

### ISSUE THREAD

**Issue by shaka87** [GreenleafLab/ArchR#115]
I really like ArchR. There is one feature that I am missing: highlighting cells when plotting
embeddings. So far the work around is to create a new variable that splits the cells into
two groups and then to use two different colors to plot that variable with name = '...'. 

The Seurat package has this option for DimPlot() which can be used with cells.highlight = '...'.

Could you add an option to plotEmbedding() that allows to specify which cells will be highlighted? 

Thank you!

livius

**Comment by rcorces** [comment]
Thanks for the feature request. This is reasonable though not plug and play to implement given the way `plotEmbedding()` currently works. Our original intention was for users to do what you recommended (add a new column to `cellColData` that defines the desired comparison). We will keep this request open for now but it may be lower priority in the short term while we deal with bugs since there is a plausible work around.

Having a clear use case for this might elevate its priority though if it is something that users would do very frequently. Maybe you could describe the situation where you have specific cell names but those cell names dont correspond to a biologically relevant group that you would want stored in `cellColData`. In my typical use of ArchR, I am rarely working with cell names.

Is the desired functionality to work exactly as `cells.highlight` in `Seurat`?

**Comment by shaka87** [comment]
Thank you for your reply. I understand that this will be low priority given that it can be worked around. Yes, if it were possible to specify cells to be highlighted exactly as in Seurat, that would be awesome. If you do implement such a functionality, then maybe you could also allow an option for color and size of the highlighted cells at the same time. 

Indeed I have two use cases for cells.highlight - generally this would be useful when integrating additional information:

- highlighting TCR or BCR clones (obviously that is an application of scRNA-seq, but if I integrate scRNA-seq with scATAC-seq data, then I would like to try to highlight certain clonotypes using the predictedCell ID)
- highlighting mutational information of individual single cells

**Comment by jgranja24** [comment]
Hi @shaka87, 

Can you add a screenshot/figure of what it is you are requesting. Im not familiar with Seurats DimPlot to this extent.

Best

Jeff

**Comment by shaka87** [comment]
Hey Jeff, 

attached is a screen shot of a (trivial) example of using DimPlot to highlight 3 subpopulations.
I would like to be able to highlight individual subpopulations with ArchR - not necessarily defined by clustering - in order to demonstrate additional aspects obtained through other assays. 
This could be a subclone defined by a mutation that spans multiple clusters and I would like to show its location on the umap. 

Thank you, 

livius

<img width="1624" alt="Screen Shot 2020-05-07 at 11 58 47 PM" src="https://user-images.githubusercontent.com/62758571/81348691-d9c56600-90be-11ea-9e16-d7a9cd815be0.png">

**Comment by jgranja24** [comment]
Got it. So basically all non highlighted cells will be grey. If this is correct i can add this feature.

**Comment by shaka87** [comment]
Yes! :)

**Comment by jgranja24** [comment]
This is now functional in the new master update. See `highlightCells` in `plotEmbedding`.

**Comment by shaka87** [comment]
@jgranja24 cool, it works fine. I don't know if you intended this, but you can even play with the colors (for example background black and highlighted cells in blue):

`plotEmbedding(pbmc, highlightCells = pbmc$cellNames[which(pbmc$manual.clusters == 'cluster.of.interest')], plotAs = 'points', pal = c('blue','black'))`
