### ISSUE TITLE
bugs in getGroupBW

### ISSUE THREAD

**Issue by haibol2016** [GreenleafLab/ArchR#1163]
@rcorces
[Line 330 in GroupExport.R](https://github.com/GreenleafLab/ArchR/blob/master/R/GroupExport.R)
`nTiles <- trunc(chromLengths[availableChr[k]] / tileSize) + 1`  should be changed to
```{r}
      nTiles <- chromLengths[availableChr[k]] / tileSize
      if (nTiles%%1 != 0)
      {
         nTiles <- trunc(nTiles) + 1
      }
```
Because if a chromosome can be divided into exactly N tiles, you don't need to add 1 extra tile.

**Comment by rcorces** [comment]
Looks right to me. Patched in `release_1.0.2` via https://github.com/GreenleafLab/ArchR/commit/84c8ff41940d8ce1ab2efa8237f3376a257a331d

**Comment by rcorces** [comment]
Thanks for reporting!

**Comment by shycheng** [comment]
Hello, I encountered a similar issue while using the getGroupBW function and managed to identify a potential bug related to the calculation of the number of tiles (nTiles). Specifically, if a fragment is located at the very end of a chromosome, the expression trunc(end(fragik) / tileSize) + 1 can mistakenly result in nTiles + 1 instead of nTiles. I resolved this issue by modifying the indexing in the following manner:
i <- pmin(pmax(c(trunc(start(fragik) / tileSize), trunc(end(fragik) / tileSize)) + 1, 1), nTiles)
This change ensures that the index remains within the correct bounds, thus preventing any overflow errors. The error disappeared after applying this modification.
