### ISSUE TITLE
Test statistic for determining number of dimention in iterativeLSI function

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#120]
It would be nice if you would add some test statistic for determining the optimal number of the dimension for dimensionality reduction in itertativeLSI function (sth like explained variance-dimension plot). Currently, it's an adhoc, and just visual inspection can be misleading ...

**Comment by jgranja24** [comment]
The top 30 dimensions are used by default which in our hands has worked broadly. The % variance is not the same here because LSI in ArchR standardizes the SVD components. Therefore this would be misleading to interpret. ArchR filters out correlated components with depth which is the most important part of dimensionality reducion.

**Comment by CSBioAzim** [comment]
@jgranja24 , thanks!
