### ISSUE TITLE
Error in H5Fopen(file): Unable to open HDF5 file when using subsetArchRProject to create new arrow files - working on a cluster 

### ISSUE THREAD

**Issue by kirakoko** [GreenleafLab/ArchR#1219]
Hey everyone, I am so sorry to bother you but as many people had this issue I would like to share the error message and would seek for help as i am also new in computational stuff...I am working on a cluster 

inputFiles <- c('test'= "/outs/atac_fragments.tsv.gz")
inputFiles
test
"/outs/atac_fragments.tsv.gz"
export HDF5_USE_FILE_LOCKING=FALSE, RHDF5_USE_FILE_LOCKING=FALSE
Error: unexpected symbol in "export HDF5_USE_FILE_LOCKING"
HDF5_USE_FILE_LOCKING=FALSE
HDF5_USE_FILE_LOCKING
[1] FALSE
addArchRGenome('hg38')
Setting default genome to Hg38.
addArchRThreads(threads = 1)
Setting default number of Parallel threads to 1.
ArrowFiles <- createArrowFiles(

inputFiles = inputFiles,
sampleNames = inputFiles,
minTSS = 4, #Dont set this too high because you can always increase later
minFrags = 1000,
addTileMat = TRUE,
addGeneScoreMat = TRUE,
subThreading = FALSE
)
Using GeneAnnotation set by addArchRGenome(Hg38)!
Using GeneAnnotation set by addArchRGenome(Hg38)!
ArchR logging to : ArchRLogs/ArchR-createArrows-47ed44daa662-Date-2021-12-06_Time-11-46-50.log
If there is an issue, please report to github with logFile!
2021-12-06 11:46:50 : Batch Execution w/ safelapply!, 0 mins elapsed.
2021-12-06 11:46:50 : (/outs/atac_fragments.tsv.gz : 1 of 1) Reading In Fragments from inputFiles (readMethod = tabix), 0.001 mins elapsed.
2021-12-06 11:46:50 : (/outs/atac_fragments.tsv.gz : 1 of 1) Tabix Bed To Temporary File, 0.001 mins elapsed.
2021-12-06 11:46:50 : ERROR Found in .tabixToTmp for (/outs/atac_fragments.tsv.gz : 1 of 1)
LogFile = ArchRLogs/ArchR-createArrows-47ed44daa662-Date-2021-12-06_Time-11-46-50.log

<simpleError in H5Fcreate(file): HDF5. File accessibility. Unable to open file.>

2021-12-06 11:46:50 : createArrowFiles has encountered an error, checking if any ArrowFiles completed..
ArchR logging successful to : ArchRLogs/ArchR-createArrows-47ed44daa662-Date-2021-12-06_Time-11-46-50.log

if someone has a solution i would appreciate it! thank you

and i trief the solution from this very helpful post https://github.com/GreenleafLab/ArchR/issues/248 but unfortunately it didn't work

**Comment by rcorces** [comment]
Hi @kirakornienko! Thanks for using ArchR! I am currently on paternity leave and will not be responding to any issues or discussion threads. I plan to be back in late January and will do my best to address your issue then.<br />
In the meantime, it is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment. Search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.<br />
If you are able to solve your issue, please post the solution and close this issue post. <br />
Otherwise __if you would like my help when I return, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by kirakoko** [comment]
it solved itself!
