### ISSUE TITLE
 getMarkerFeatures failed

### ISSUE THREAD

**Issue by HeChao7021** [GreenleafLab/ArchR#1223]
Hi, when I use the function of getMarkerFeatures, the error comes like following: 
> markerTest <- getMarkerFeatures(
+   ArchRProj = projHeme5, 
+   useMatrix = "PeakMatrix",
+   groupBy = "Clusters2",
+   testMethod = "wilcoxon",
+   bias = c("TSSEnrichment", "log10(nFrags)"),
+   useGroups = "companion",
+   bgdGroups = "epidermis"
+ )
ArchR logging to : ArchRLogs/ArchR-getMarkerFeatures-92a1451f745c-Date-2021-12-10_Time-17-13-17.log
If there is an issue, please report to github with logFile!
2021-12-10 17:13:18 : Matching Known Biases, 0.013 mins elapsed.
Error in .matchBiasCellGroups(input = colDat, groups = groups, useGroups = useGroups,  : 
  all(useGroups %in% unique(paste0(groups))) is not TRUE

There are no NAs introduced by the addClusters() function:
> table(projHeme5$Clusters,useNA='ifany')
  C1  C10  C11  C12  C13  C14  C15  C16   C2   C3   C4   C5   C6   C7   C8   C9 
  27   64  104  451   19  927  227  568   33   23  241   32 1228 1078 1501  712 

Look forward for your reply, thanks

**Comment by rcorces** [comment]
Hi @HeChao7021! Thanks for using ArchR! I am currently on paternity leave and will not be responding to any issues or discussion threads. I plan to be back in late January and will do my best to address your issue then.<br />
In the meantime, it is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment. Search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.<br />
If you are able to solve your issue, please post the solution and close this issue post. <br />
Otherwise __if you would like my help when I return, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by HeChao7021** [comment]
Oh, best wishes! And thank you again.
