### ISSUE TITLE
Error Accessing Log File in Arrow File Creation Step

### ISSUE THREAD

**Issue by Wanda-Sankey** [GreenleafLab/ArchR#1228]
[ArchR-createArrows-fa34dd91265-Date-2021-12-10_Time-15-53-29.log](https://github.com/GreenleafLab/ArchR/files/7713730/ArchR-createArrows-fa34dd91265-Date-2021-12-10_Time-15-53-29.log)

I am trying to create an Arrow file and keep running into this bug. I am running ArchR on an EC2 instance running linux. 

Here is the code I am using to generate the bug: 

```
## removing the requirement for a specific prefix for chromosome names
addArchRChrPrefix(chrPrefix = FALSE)

## Importing the blocklist bed file as a granges object
gblocklist <- import(blocklist)

## Using the reference BSgenome package and blocklist to set the reference genome
genomeAnnotation <- createGenomeAnnotation(genome = BSgenome.ref.na.1.0, filter = FALSE, filterChr = NULL, blacklist = gblocklist)

## Importing the gtf file into a granges object
granges <-import(gtf)

## Adding a column named symbol to the granges object which is what ArchR uses to relate between TSS, exons, and genes
granges$symbol = mcols(granges)[, c('gene_id')]

## Setting geneAnnotation for the reference using the gtf files
geneAnnotation <- createGeneAnnotation(
  TSS = resize(granges[mcols(granges)[, c('type')] == "transcript"], width = 1), 
  exons = granges[mcols(granges)[, c('type')] == "exon"], 
  genes = granges[mcols(granges)[, c('type')] == "transcript"]
)


## Setting path to samples and getting sample names
sample <- list.files(pattern = "\\.final.bam$")
samplename <- gsub(".final.bam", "", list.files(pattern = "\\.final.bam$"))


## Creating arrow files
ArrowFiles <- createArrowFiles(
  inputFiles = sample,
  sampleNames = samplename,
  geneAnnotation = geneAnnotation,
  genomeAnnotation = genomeAnnotation,
  minTSS = 0, 
  minFrags = 1, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE,
  excludeChr = c("None"),
  bcTag = "DB",
  # threads = 1,
  subThreading = FALSE,
  bamFlag = list(isMinusStrand = FALSE, isProperPair = TRUE, isDuplicate = FALSE),
  force = TRUE
)
```

I would expect an arrow file to be generated. I am unsure as to why it isn't. This bug only persists on some of the datasets I run, which confuses me because if it was as simple as a file permission issue I wouldn't expect it to fail on only some samples.

**Comment by rcorces** [comment]
Hi @Wanda-Sankey! Thanks for using ArchR! I am currently on paternity leave and will not be responding to any issues or discussion threads. I plan to be back in late January and will do my best to address your issue then.<br />
In the meantime, it is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment. Search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.<br />
If you are able to solve your issue, please post the solution and close this issue post. <br />
Otherwise __if you would like my help when I return, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment]
closing in an effort to tidy up issues. If you still need help, post here and I will re-open.
