### ISSUE TITLE
plotEmbedding() not accepting customized color palette

### ISSUE THREAD

**Issue by Arinze-BioX** [GreenleafLab/ArchR#1240]
**Attach your log file**
[ARCHR-~1.LOG](https://github.com/GreenleafLab/ArchR/files/7810649/ARCHR-.1.LOG)

**Describe the bug**
Pardon me if this is not a bug but just due to my lack of knowledge. I have installed the latest version of ArchR, and also looked through the documentation but can't seem to get a solution.

I am trying to set the color palette used for highlighting cell points on a UMAP using the code below:

```
plotEmbedding(
  ArchRProj = Proj_mmInjAllMuSC,
  embedding = "UMAP_batch",
colorBy = "cellColData",
  name = "Variable_in_cellColData",
  size = 1, pal=c("grey", "red"),  sampleCells = NULL,
  highlightCells = Vector_of_CellNames,
  baseSize = 10,
  plotAs = "points")
```

This produces a figure with no highlights and no labels, just a umap with cell points but no color at all. Since the pal option accepts color palettes, expectedly, I should be able to supply a customized string of colors similar to those in the ArchRpalettes and change the colors to a desired one. However, this seems to break the plotting function.

**Expected behavior**
I expect that the pal option should be a character vector of colors. Thus, I expect to get a umap with some cells highlighted with a red color and other cells colored grey.

**Screenshots**
The figure produced:
![image](https://user-images.githubusercontent.com/64432306/148130214-286a4e66-0f95-497f-8d1f-3bcd82f5ac46.png)

**Additional context**
When I remove the 'pal=c("grey", "red"),' option, it plots correctly, but with a color that is not what I want. Interestingly, when I do same for another vector of cellNames, it plots in a different color. 

Some months ago, the above code worked, using an older ArchR version (I had generated the plot I am trying to replot now previously).

Another issue I noticed that might be related is, I am now unable to edit individual points on the UMAP plot. I can edit points for UMAP I plotted months ago using an older version.

**Comment by rcorces** [comment]
Hi @Arinze-BioX! Thanks for using ArchR! I am currently on paternity leave and will not be responding to any issues or discussion threads. I plan to be back in late January and will do my best to address your issue then.<br />
In the meantime, it is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment. Search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.<br />
If you are able to solve your issue, please post the solution and close this issue post. <br />
Otherwise __if you would like my help when I return, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment]
Better late than never? Or perhaps this will help others down the line.

The key to getting this to work is using the correct names for the palette. Otherwise ArchR gets confused.

By default, ArchR will plot the highlighted cells as red:
```
plotEmbedding(
  ArchRProj = projHeme5,
  embedding = "UMAP",
  colorBy = "cellColData",
  name = "Clusters2",
  size = 1,
  sampleCells = NULL,
  highlightCells = getCellNames(ArchRProj = projHeme5)[which(projHeme5@cellColData$Clusters2 == "Mono")],
  baseSize = 10,
  plotAs = "points")
```
![image](https://user-images.githubusercontent.com/10343046/163675962-3c212a9e-e9ad-474e-aa6d-02f31a96c3e2.png)


You can pass a custom palette but it needs to be a properly named vector, with one value corresponding to the value in the `cellColData` column indicated by the `name` param. For example, below I am highlighting cells with the value "Mono" in "Clusters2". So I pass a palette that includes a named value for "Mono" and a named value for "Non.Highlighted".

```
plotEmbedding(
  ArchRProj = projHeme5,
  embedding = "UMAP",
  colorBy = "cellColData",
  name = "Clusters2",
  size = 1,
  pal=c("Mono" = "green", "Non.Highlighted" = "lightgrey"),
  sampleCells = NULL,
  highlightCells = getCellNames(ArchRProj = projHeme5)[which(projHeme5@cellColData$Clusters2 == "Mono")],
  baseSize = 10,
  plotAs = "points")
```
![image](https://user-images.githubusercontent.com/10343046/163675982-ab15ebcc-2fa3-4d11-adb2-1bb4d2e7f6e2.png)

**Comment by rcorces** [comment]
Should have mentioned that I made this more explicit in the parameter definition for `pal`
https://github.com/GreenleafLab/ArchR/commit/6feac133d5a5bc8a14e589bfc999329bb39e8f6b
