### ISSUE TITLE
Ridges in plotGroups out of data range

### ISSUE THREAD

**Issue by Zepeng-Mu** [GreenleafLab/ArchR#1249]
Hello,
I noticed the `ridge` version in `plotGroups` sometimes does not depict the exact of data and can look confusing. For example, below I'm plotting `TSSEnrichment` after filtering my data with min TSS above 4.
![Screen Shot 2022-01-10 at 16 51 45](https://user-images.githubusercontent.com/21952317/148851698-8c28dad7-e656-4f1b-bfe1-ba18b1449f0e.png)
In cluster 4, there are some density below 4 (4 is the black vline). But everything looks OK in violin plots.
![Screen Shot 2022-01-10 at 16 51 35](https://user-images.githubusercontent.com/21952317/148852023-2d06c3b7-f8a7-4ef8-9f76-64d5b3a3387e.png)
As plotted above, there is no points below 4 in the violin plot.

Thanks in advance!

**Comment by rcorces** [comment]
Hi @Zepeng-Mu! Thanks for using ArchR! I am currently on paternity leave and will not be responding to any issues or discussion threads. I plan to be back in late January and will do my best to address your issue then.<br />
In the meantime, it is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment. Search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.<br />
If you are able to solve your issue, please post the solution and close this issue post. <br />
Otherwise __if you would like my help when I return, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment]
@Zepeng-Mu - Trying to address some of these older issues now that I'm back at work. The problem here is with how ggridges works. This is explained here - https://stackoverflow.com/questions/49906240/stop-geom-density-ridges-from-showing-non-existent-tail-values

> The ggridges package provides two main geoms, geom_ridgeline and geom_density_ridges. The former takes height values directly to draw ridgelines, and the latter first estimates data densities and then draws those using ridgelines

So what is being plotted is actual the estimated data density.

One solution would be to set the `xlim` of the plot from ggGroup to stop at 0, though it is worth noting that even this still isnt totally accurate (explained in the stackoverflow post linked above).
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/GgplotUtils.R#L729

I'm not sure if the above solution is better but I'm happy to implement it.

**Comment by Zepeng-Mu** [comment]
Hello, thanks so much for this information.
Plotting ggridges is not necessary for what I'm doing, so I will just use other ways to plot the data.
