### ISSUE TITLE
[Question] Setting Global genome

### ISSUE THREAD

**Issue by hukai916** [GreenleafLab/ArchR#1263]
Hi core developers,

Quick question. Do I must set global genome if I use a custom genome annotation when creating the ArchRProject:
```
ArchRProject(
  ArrowFiles = c(\\"\$arrows\\"),
  geneAnnotation = geneAnnotation,
  genomeAnnotation = genomeAnnotation
)
```
In this case, I used a custom geneAnnotation and genomeAnnotation that are not supported by ArchR yet. My question is, do I also need to specify something like `addArchRGenome(xxx)`? In other words, will the annotation info be carried with the ArchRProject object? I saved the ArchRProject obj into a RDS file and later load from RDS, will the annotation info be lost in such cases?

Another related question is about `addArchRThreads()`, will the threads info be carried with the ArchRProject object or do I must invoke it overtime I start a new R session?

Thanks!

**Comment by rcorces** [comment]
Hi @hukai916! Thanks for using ArchR! I am currently on paternity leave and will not be responding to any issues or discussion threads. I plan to be back in late January and will do my best to address your issue then.<br />
In the meantime, it is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment. Search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.<br />
If you are able to solve your issue, please post the solution and close this issue post. <br />
Otherwise __if you would like my help when I return, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by rcorces** [comment]
Finally getting around to some of these older issues that were posted while I was out.
No - with a custom genome, you do not need to use `addArchRGenome()`

Threads info is not carried with the ArchRProject object. It must be set each time you restart R. This allows for more flexibility for the end user.
