### ISSUE TITLE
error with combining two 10XFeatureMatrices when using 2 Multiome datasets

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#1266]
Hi @emmawwinchester , @rcorces , @jgranja24 
I followed your script while merging two multiome datasets. It worked for me in the past but now I'm encountering an error when attempting to merge the same datasets.
<img width="881" alt="Screen Shot 2022-01-21 at 10 23 17 AM" src="https://user-images.githubusercontent.com/64283689/150563046-c8707fc8-61be-45ea-9794-7a4b10bd5aa0.png">
Can you offer any suggestions?
[ArchR-addGeneExpressionMatrix-ed685c5946c-Date-2022-01-21_Time-10-14-20.log](https://github.com/GreenleafLab/ArchR/files/7915201/ArchR-addGeneExpressionMatrix-ed685c5946c-Date-2022-01-21_Time-10-14-20.log)
[ArchR-addGeneExpressionMatrix-ed6820611ae9-Date-2022-01-21_Time-10-15-52.log](https://github.com/GreenleafLab/ArchR/files/7915203/ArchR-addGeneExpressionMatrix-ed6820611ae9-Date-2022-01-21_Time-10-15-52.log)

_Originally posted by @sylestiel in https://github.com/GreenleafLab/ArchR/issues/507#issuecomment-1018662720_

**Comment by rcorces** [comment]
Hi @sylestiel! Thanks for using ArchR! I am currently on paternity leave and will not be responding to any issues or discussion threads. I plan to be back in late January and will do my best to address your issue then.<br />
In the meantime, it is worth noting that there are very few actual bugs in ArchR. If you are getting an error, it is probably something specific to your dataset, usage, or computational environment. Search the previous [Issues](https://github.com/GreenleafLab/ArchR/issues), [Discussions](https://github.com/GreenleafLab/ArchR/discussions), [function definitions](https://www.archrproject.com/reference/index.html), or the [ArchR manual](https://www.archrproject.com/bookdown/index.html) and you will likely find the answers you are looking for.<br />
If you are able to solve your issue, please post the solution and close this issue post. <br />
Otherwise __if you would like my help when I return, you must respond to the following questions__ unless your original post already contained this information:
__1.__ If you've encountered an error, have you already searched previous Issues to make sure that this hasn't already been solved?
__2.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.
__3.__ Did you post your log file? If not, add it now.

**Comment by sylestiel** [comment]
Congratulations Dr. Corces!

Yes, I'm aware that you are on leave. Did not expect a response from you till your return.
Response to your questions.
1) I did a search in the discussions window and found a post that helped in the past with the exact same datasets
2) The tutorial does not address merging of Multiome datasets
3) Yes, the log file has been provide in the earlier post.

Thanks!

**Comment by waltno** [comment]
Additional errors with Mulitome data!

**Out put**
Error in h5read(x, paste0(useMatrix, "/Info/Units")) : 
  Object 'GeneExpressionMatrix/Info/Units' does not exist in this HDF5 file.

**code**
```
files<-paste(samps, "/filtered_feature_bc_matrix.h5", sep="")

seRNA <- import10xFeatureMatrix(input = files, names = samps)

seRNAmo<-cbind(assay(seRNA[[1]]), assay(seRNA[[2]]), assay(seRNA[[3]]) ,assay(seRNA[[4]]), assay(seRNA[[5]]), assay(seRNA[[6]]),assay(seRNA[[7]]),assay(seRNA[[8]]), assay(seRNA[[9]]))

seRNA2<-SummarizedExperiment(assays=list(counts=seRNAmo), rowRanges= rowRanges(seRNA[[1]]))

ew4<-addGeneExpressionMatrix(input=ew4, seRNA=seRNA2, force = T)

ew4 <- addIterativeLSI(
    ArchRProj = ew4, 
    clusterParams = list(
      resolution = 0.2, 
      sampleCells = 10000,
      n.start = 10
    ),
    saveIterations = FALSE,
    useMatrix = "GeneExpressionMatrix", 
    depthCol = "Gex_nUMI",
    varFeatures = 2500,
    firstSelection = "variable",
    binarize = FALSE,
    name = "LSI_RNA"
)
```
[ArchR-addIterativeLSI-8dff4e3441f0-Date-2022-02-02_Time-16-10-01.log](https://github.com/GreenleafLab/ArchR/files/7990864/ArchR-addIterativeLSI-8dff4e3441f0-Date-2022-02-02_Time-16-10-01.log)

**Comment by rcorces** [comment]
@waltno - Is ew4 some previously subsetted project? The error you are getting shouldnt happen. The Units group is added here:
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/ArrowWrite.R#L71
and `.initializeMat()` is passed all of the requisite info here for a GeneExpressionMatrix:
https://github.com/GreenleafLab/ArchR/blob/968e4421ce7187a8ac7ea1cf6077412126876d5f/R/MatrixGeneExpression.R#L220

If you did some subsetting to ew4, its possible that something would have gotten off track.

In the future, please open new issues unless the error is related (which it doesnt appear to be?)

@sylestiel - if you still want help please let me know.

**Comment by rcorces** [comment]
@sylestiel - see the other thread for the solution:
https://github.com/GreenleafLab/ArchR/issues/507#issuecomment-1043259579

Closing this one.

**Comment by sylestiel** [comment]
@rcorces 
#Import scRNA
    input <-  c("/Volumes/BKUP2/020521_Dual_scATAC_GEX/Dual_E165/outs/filtered_feature_bc_matrix.h5", "/Volumes/BKUP2/020521_Dual_scATAC_GEX/Dual_P2/outs/filtered_feature_bc_matrix.h5")

#set your names variable
names <- c("E165dual","P2dual")

#set your featureType variable
featureType <- "Gene Expression"

featureMats <- lapply(seq_along(input), function(y) {
  message("Importing Feature Matrix ", y, " of ", length(input))
  ArchR:::.importFM(featureMatrix = input[y], featureType = featureType, 
            name = names[y])
})


seRNAcombined<-cbind(assay(featureMats[[1]]), assay(featureMats[[2]]))

seRNA<-SummarizedExperiment(assays=list(counts=seRNAcombined), rowRanges= rowRanges(featureMats[[1]]))
seRNA

Can you clarify if this script is correct? If not can you paste the current script  for combining the h5 files for multiple samples for ease of understanding.
