### ISSUE TITLE
on chromvar deviations per sample

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#140]
Hello,

Thanks again for this great package! I have been noticing some possibly odd deviations across samples when overlaid on UMAPs. On this regard, given that chromvar deviations are calculated indipendently per each sample (according to the manual and paper) shouldnt this lead to coverage-driven bias? I guess this is corrected specifying the bias argument in the function getMarkerFeatures but how does it work in details? 

Thanks !!

**Comment by jgranja24** [comment]
chromVAR deviations are computed per cell independently hereby eliminating this type of bias. However, in extreme cases this coverage bias can lead to biases in the deviation scores. If you suspect this, use the "deviations" instead of "z". This is not affected by depth but is not normally used because the units magnitude are a little harder to interpret relatively. To do this for example
use deviations:motif instead-

`plotEmbedding(ArchRProj=ArchRProj, useMatrix = "MotifMatrix", name = "deviations:motif")`

Hopefully this helps.

Best

Jeff

**Comment by Brawni** [comment]
Hi Jeff,

thanks for the input, I can see slight differences in the UMAPs but not as much as i'd hoped. I will run chromvar again with other pipelines and report back if I see some discrepancies.

Thanks again!

**Comment by rcorces** [comment]
Closing. Re-open if you feel your question has not been resolved.
