### ISSUE TITLE
advice on analyzing a particular tf (subsetted peak set?)

### ISSUE THREAD

**Issue by juliabelk** [GreenleafLab/ArchR#144]
Not sure if this is a feature request or a doc request.

I would like to make a subsetted peak set of only peaks containing a particular TF motif and do differential peaks, etcetera, with that. What's the best way to do this in ArchR?

Also, is it possible to do footprinting at a single motif location? To figure out whether it seems like the TF is bound or not at a specific genomic location?

For context, I have two scATAC samples, one from a WT mouse and one from a mouse with a point mutation in a TF. I want to do some analysis to figure out what the TF might be doing differently between the samples (chip-seq or hichip would be great but so far I only have scATAC). Any advice for this scenario, beyond the two analyses I described above, would also be welcome.

Thank you!

**Comment by jgranja24** [comment]
> I would like to make a subsetted peak set of only peaks containing a particular TF motif and do differential peaks, etcetera, with that. What's the best way to do this in ArchR?

Just do differential analysis genome wide and then subset the seMarker by that. If you want to as well you can re-adjust your pvalues to FDR with p.adjust in R. The normalization in ArchR for peaks is based on the reads in TSS regions thus has no relationship to the total peak set.

> Also, is it possible to do footprinting at a single motif location? To figure out whether it seems like the TF is bound or not at a specific genomic location?

This really isnt something that can be said from this analysis. There is a lot of scrutiny over footprinting single locations because of tn5 bias that in aggregated can be modeled but has a much higher error rate for single loci. That being said you can just use 1 range for footprinting i believe.

**Comment by juliabelk** [comment]
thanks
