### ISSUE TITLE
Removed cells persist in plots

### ISSUE THREAD

**Issue by concatenize** [GreenleafLab/ArchR#146]
Hi ArchR devs! We are having some trouble making plots with a subset of our data: the plots still contain all cells. 

**Attach your log file**
[ArchR-plotEmbedding-133d63766783c-Date-2020-05-18_Time-17-43-18.log](https://github.com/GreenleafLab/ArchR/files/4646972/ArchR-plotEmbedding-133d63766783c-Date-2020-05-18_Time-17-43-18.log)

**Describe the bug**
When I subset 100 cells and make a plot, the remaining cells still appear in the plot.

**To Reproduce**
Here's a script to reproduce the behavior on the tutorial data.
[subsetting.R.txt](https://github.com/GreenleafLab/ArchR/files/4646979/subsetting.R.txt)

**Expected behavior**
Plots should contain only cells selected during subsetting.

**Comment by jgranja24** [comment]
plotEmbedding uses an existing embedding in your ArchRProject. If you subset the cells in the project this has no effect on plotEmbedding. This is because there are a few functions that deal with the full data set ie impute weights. If you want to do this subsetting you should add a new embedding to your project of those 100 cells then use plotEmbedding as you did in your script. Sorry if this is not desired but its a bit difficult to control from plotEmbedding. I think maybe a better adder so to speak for custom embeddings is something to be desired in this case.

**Comment by concatenize** [comment]
I would interpret this as a bug in `[`, not a problem with `plotEmbedding`. But yes, I think I see what you mean, and that seems like a good solution.

**Comment by jgranja24** [comment]
I see I can make it throw an error as well if not all names are equal.

**Comment by jgranja24** [comment]
I added a check in plotEmbedding to help with error messaging.

Closing this issue feel free to open if you have further questions or issues.
