### ISSUE TITLE
Is it possible to read from Cellranger-atac aggr and interoperate with Loupe Browser?

### ISSUE THREAD

**Issue by Sophiesze** [GreenleafLab/ArchR#167]
Hi GreenleafLab,

Thanks for providing such user-friendly tools. 

First, I am just wondering is the ArrowFiles can only be created from 10X Cellranger-count? Is it possible to be created from Cellranger-aggr? I found that when I put a fragments file which is already integrated with several samples, It may not be above to do the downstream analysis because there is only one sample presented in the ArchRProject. 

Second, Is it possible that ArchR interoperates with Loupe Browser? The reason why I ask this question is that I think it will be quite convenient to interoperate with Loupe Browser and R packages by importing the Cloupe file after aggring when I try to define different cell types. 

Thanks in advance for your help!

Best,
Sophie

**Comment by jgranja24** [comment]
> First, I am just wondering is the ArrowFiles can only be created from 10X Cellranger-count? Is it possible to be created from Cellranger-aggr? I found that when I put a fragments file which is already integrated with several samples, It may not be above to do the downstream analysis because there is only one sample presented in the ArchRProject.

I am not aware too much of how Cellranger-aggr works. The challenge with merging fragment files is that it becomes a bit difficult to determine sample specific information. Additionally ArchR is optimized too handle many samples which is preferential. Lastly, tools like doubletScores assume there is 1 sample rather than aggregates. I could provide a tool to split the aggregated file if thats what you are interested in.

> Second, Is it possible that ArchR interoperates with Loupe Browser? The reason why I ask this question is that I think it will be quite convenient to interoperate with Loupe Browser and R packages by importing the Cloupe file after aggring when I try to define different cell types.

From 10x website -
<img width="851" alt="Screen Shot 2020-05-22 at 10 52 29 AM" src="https://user-images.githubusercontent.com/25017655/82695665-607b5680-9c1a-11ea-8187-2ec057e39513.png">

ArchR should be able to do all the following analysis with ease and some. You can always add external info into your ArchRProject from outside sources.

Best

Jeff

**Comment by Sophiesze** [comment]
Thank you so much for your help!
