### ISSUE TITLE
Metrics for filtering

### ISSUE THREAD

**Issue by Brawni** [GreenleafLab/ArchR#171]
Hi!

Other packages such as cell ranger and Signac apply filtering based on reads in peaks or TSS whereas in the ArchR pipeline only the total number of fragments and TSSEnrichment are used as default filtering as described in section 1.7 of the manual. Do you think these two metrics are sufficient to select for good quality cells or refining the filtering using Reads in TSS / peaks should be also considered for default filtering? Also filtering for nucleosome ratio and blacklist enrichment should also be added somewhere in the tutorial / manual, don't you think?

Thanks!

**Comment by rcorces** [comment]
@jgranja24 - Thoughts on adding the possibility for filtering for nuclesome ratio / blacklist enrichment?

In terms of FRIP or Reads in Promoters, we do not believe that these metrics offer any benefits over using the TSS enrichment score and, in our hands, the provided QC metrics are sufficient (and superior).

For FRiP, you must first define a peak set. This becomes problematic in single-cell data because, by default, you must define your peak set before clustering because you should filter out low quality cells before clustering. For this reason, FRiP is typically calculated per-cell based on a peak set identified from the merged set of all cells. This obscures cell type-specific peaks from lowly abundant cell types (less than 20%) and thus biases more abundant cell types to having better quality scores. This is not desirable.

For FIP, we find that simply summing the reads in promoter regions does not provide as clear a stratification of high quality cells from low quality cells. 

![image](https://user-images.githubusercontent.com/10343046/83170247-1803e300-a0c9-11ea-941b-1976a32218fe.png)

I have added a section on this to the documentation. this will appear when we push the next large documentation update in the next few weeks.

**Comment by Brawni** [comment]
Thanks for your answer! 
I was more thinking on using the FRIP filtering as a second pass of filtering after the clusters-aware peak calling has been run. Also, FRIP may be more robust as it takes into account of all peaks and not of only those on TSS?
Btw these filtering plots are amazing but can't find a function to generate them other than running again the createArrowFiles function

Thanks!

**Comment by rcorces** [comment]
I understand what you want to do now. You can always filter additional cells from your project using `subsetArchRProject()` and identifying the cells you would like to keep. In this case, you could calculate FRiP based off the sum of counts in the `peakMatrix`

The plots are just a wrapper around the ArchR `ggPoint()` function using `colorDensity = TRUE`. So you should be able to regenerate them using the information stored in `cellColData`.

**Comment by Brawni** [comment]
cool thanks!
