### ISSUE TITLE
markerTest

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#172]
I obtained marker peaks by analyzing two of the clusters that I was interested in, and I visualized the first few peaks in Browser Tracks, and they made sense. 
Then I used those markerTest set for motif enrichment analysis.

```
markerTest

class: SummarizedExperiment 
dim: 349961 1 
metadata(2): MatchInfo Params
assays(6): Log2FC Mean ... AUC MeanBGD
rownames(349961): 1 2 ... 349960 349961
rowData names(4): seqnames idx start end
colnames(1): cluster1
colData names(0):
```

```
motifsUp <- peakAnnoEnrichment(
    seMarker = markerTest,
    ArchRProj = projHeme5,
    peakAnnotation = "Motif",
    background = c("cluster2"),
    cutOff = "FDR <= 0.1 & Log2FC >= 0.5"
  )
```

The result that I get is kinda inconsistent with the marker peaks. What I mean by that is that marker peak X is more expressed in cluster2 (which is what we were expecting to see), but the motif enrichment says that the corresponding TF is enriched in cluster 1 and not 2. I thought you may have a better insight into why we are seeing such a thing? biologically we are certain that the TF should be enriched in cluster1 and not cluster2, and differential peak analysis between those two clusters confirms that.

**Comment by jgranja24** [comment]
Hi @rojinsafavi,

I may need a little more information regarding what you are asking. One thing to be aware of when analyzing motifs is that they may be a little misleading to which TF they relate to. There are numerous examples where TFs have multiple motifs associated and thus can be difficult to track down. I am a little confused how you are certain that because of certain peaks being differential you conclude that a TF is regulating those peaks without looking at the motif occurrences in those peaks. `peakAnnoEnrichment` is just a hypergeometric test for motif enrichment. Have you tried `addDeviationsMatrix` which is a completely unbiased approached to surveying TF enrichment? If that disagrees as well than maybe the motif you are looking into is wrong and maybe check other TFs in the same family. I would strongly recommend looking at chromVAR deviations to help aid your analysis. 

Best of luck

Jeff

**Comment by rcorces** [comment]
@rojinsafavi - let us know if you still need help with this issue. If so, please provide more information and address Jeff's questions above. If not, feel free to close. Thank you!

**Comment by rojinsafavi** [comment]
@rcorces I am going to give a try today, and will let you know how things go! thank you. I'll close the issue by tonight if I the issue is resolved :-)

**Comment by rojinsafavi** [comment]
This is what I was referring to. the first plot is chromVAR deviation for motif X, and the second plot is the geneintegeration matrix plot for TF X

<img width="337" alt="Screen Shot 2020-05-29 at 12 37 08 PM" src="https://user-images.githubusercontent.com/19545198/83298621-a51e6900-a1a9-11ea-804e-fab6141317c8.png">
<img width="343" alt="Screen Shot 2020-05-29 at 12 37 40 PM" src="https://user-images.githubusercontent.com/19545198/83298626-a6e82c80-a1a9-11ea-851f-1bec4524bd9f.png">

**Comment by rcorces** [comment]
Can you tell us what the transcription factor is? If you are uncomfortable disclosing that information publicly, just email it to us at archr.devs@gmail.com. Also, can you show us the UMAP with the gene score instead of the gene integration matrix?

**Comment by rcorces** [comment]
Hi @rojinsafavi - I think we answered this inconsistency by email. Feel free to close if you feel your question has been answered.

For anyone coming across this issue in search of answers - different motifs for the same TF can be highly variable and this can lead to drastically different results and interpretations.

**Comment by rojinsafavi** [comment]
Thank you very much, yes I got the email and will do the analysis after my final next week, thanks again!
