### ISSUE TITLE
Questions about [2.2 Inferring scATAC-seq Doublets] and [3.6 Filtering Doublets]

### ISSUE THREAD

**Issue by Sophiesze** [GreenleafLab/ArchR#173]
Hi GreenleafLab,

I have some questions about inferring scATAC-seq Doublets. As you mentioned in **Section 2.2** and **3.6** of the full manual that if the R2 value is less than 0.9, you would recommend skipping the process of doublet prediction. However, when I processed my 10 samples, I found that 3 of the samples are less than 0.9 and the rest of it is higher than 0.9. In this case, do you still recommend skipping doublet prediction and filtering doublets? If I keep the doublets would it is a problem for the downstream analysis? 

Also, if I wanna ask that if I still insisted on doing doublet prediction and filtering doublets. Is it possible to filter Doublets from the rest of the 7 samples in which the R2 value is >0.9 instead of the whole ArchRproject? And how to do it? After quality control according to the density plot(TSSenrichment>=10, log10(nfrags)>=3.5), the total cell number is only 53936(130422 cells before QC). Would it be a problem to keep filtering doublets or it is not necessary to filter doublets after quality control? 

Thanks in advance for your answer!

Best,
Sophie

**Comment by jgranja24** [comment]
Hi @Sophiesze,

>I have some questions about inferring scATAC-seq Doublets. As you mentioned in Section 2.2 and 3.6 of the full manual that if the R2 value is less than 0.9, you would recommend skipping the process of doublet prediction. However, when I processed my 10 samples, I found that 3 of the samples are less than 0.9 and the rest of it is higher than 0.9. In this case, do you still recommend skipping doublet prediction and filtering doublets? If I keep the doublets would it is a problem for the downstream analysis?


If they are less than that value it is recommended to skip doublet filtering for those samples. By default ArchR will not filter the samples that are skipped. This is because these samples are more homogenous and thus the predictions are less accurate. You should remove them for heterogeneous samples to make sure you have no false clusters.

> Also, if I wanna ask that if I still insisted on doing doublet prediction and filtering doublets. Is it possible to filter Doublets from the rest of the 7 samples in which the R2 value is >0.9 instead of the whole ArchRproject? And how to do it? After quality control according to the density plot(TSSenrichment>=10, log10(nfrags)>=3.5), the total cell number is only 53936(130422 cells before QC). Would it be a problem to keep filtering doublets or it is not necessary to filter doublets after quality control?

As i mentioned above when you create an ArchRProject see `proj$DoubletEnrichment` or `proj$DoubletScore` and there will be NAs for the samples that did not work. Thus when you filter they will not be affected. QC is independent of doublet removal and such you should ensure that the cells you use are high quality and are doublet removed to prevent false clusters.

Best

Jeff

**Comment by Sophiesze** [comment]
Thank you so much! It works well!
