### ISSUE TITLE
addTileMatrix error

### ISSUE THREAD

**Issue by yangxueqianR** [GreenleafLab/ArchR#1751]
Hi , when I using ArchR I met this error:
```proj = addTileMatrix(proj,force = T)```
***
[1] "Bad1 (Start not greater than 0): "
IRanges object with 0 ranges and 1 metadata column:
       start       end     width |    RG
   <integer> <integer> <integer> | <Rle>
[1] "Bad2 (End greater than chromsome length): "
IRanges object with 1 range and 1 metadata column:
          start       end     width |                     RG
      <integer> <integer> <integer> |                  <Rle>
  [1]  59640472  59640633       162 | 3hpf_2#3hpf_2_merge_..

2022-11-23 20:15:40 : ERROR Found in .addTileMat for 3hpf_2 
LogFile = ArchRLogs/ArchR-addTileMatrix-7f6f19e05e0d-Date-2022-11-23_Time-20-13-29.log

<simpleError in validObject(r): invalid class “dgTMatrix” object: lengths of slots i and j must match>
***
This error occurs when I use ArchR version 1.0.2. But I was able to run the same file with ArchR version 1.0.1. 
I've found similar errors in other answers. It should be install the braches dev. But I'd like to know the cause of this error.

**Attach your log file**
[ArchR-addTileMatrix-7f6f19e05e0d-Date-2022-11-23_Time-20-13-29.log](https://github.com/GreenleafLab/ArchR/files/10075535/ArchR-addTileMatrix-7f6f19e05e0d-Date-2022-11-23_Time-20-13-29.log)

**Comment by rcorces** [comment]
Downgrading to `1.0.1` only works because back then we werent properly handling bad fragments that extend past the start or end of chromosomes. So that is definitely not the way you want to go.

That being said, the updates _should_ have fixed this problem and should be properly removing bad fragments.

If I were you, I would isolate this troubleshooting to a single fragment file. Then, let ArchR tell you which fragments are causing problems and try to manually remove them from your fragments file. If that solves the problem, then that indicates to me that there is something not functioning correctly about what ArchR is doing. Unfortunately, you're working with a species that I dont work with and so a reproducible example that would help me help you is not going to be straightforward. Pay close attention in the log file as it reports bad fragments for each chromosome independently.

**Comment by yangxueqianR** [comment]
I will try to check my fragment file. Thanks for your help.
