### ISSUE TITLE
Unable to define clusters 

### ISSUE THREAD

**Issue by Sophiesze** [GreenleafLab/ArchR#191]
Hi GreenleafLab,

Sorry at first, I think this does not belong to the tag Documentation Request. But I don't know which tag I should tag my problem.

I have been analyzing my 10X data and I found that there are some clusters that I am not able to define. Also, It seems like missing some important clusters. I wonder it is because of the way I do quality control wrong or it is because of the data. 

Thus, I try to change the cut off value(TSSenrichment and log10nf) when doing QC. But there still some clusters in the middle of the UMAP that I was not able to define and the cell numbers are not small.  I read the article that GreenleafLab published on Nature Biotechnology, the cutoff is TSS>8, log10nf>3 & <4.5. As for my data, I chose TSS>10 & log10nf>3.5 & <4.2. The pre-QC plot is attached.

I have been thinking of this problem for several days, hope you can help me with it. 

Thank you so much!

Best,
Sophie

![pre-qc](https://user-images.githubusercontent.com/53801318/83494419-d4eea900-a4e8-11ea-8087-be02bc71ccd5.jpg)
![umap](https://user-images.githubusercontent.com/53801318/83494566-0cf5ec00-a4e9-11ea-9830-72ebf6f4268f.jpg)

**Comment by rcorces** [comment]
In this case, I think your cutoffs should look like this:
![image](https://user-images.githubusercontent.com/10343046/83543774-c769fc80-a4b1-11ea-88bd-87ec6d259910.png)

We dont normally apply upper bounds on the number of fragments per cell, though if you wanted to apply one I would make it closer to 4.5 rather than 4.2.

Have you removed doublets?

Have you tried getting marker genes from gene scores for your unknown clusters?

**Comment by Sophiesze** [comment]
Thanks for your suggestions, I will try to change the arguments and run it again. 

I have already removed some doublets with the default arguments using  `filterDoublets()`. I also get the marker genes from the GenesoreMatrix. 
It is hard to define the clusters that always gathering in the middle no matter how I select the cutoff value in quality control.

Also, I'm also not sure about whether the two clusters on two side of the B cells is pDC and DC (on the top of the panel). I have already posted the MarkerUMAP below.

Thanks again for your reply!


[5-Plot-UMAP-Marker-Genes-WO-Imputation.pdf](https://github.com/GreenleafLab/ArchR/files/4720653/5-Plot-UMAP-Marker-Genes-WO-Imputation.pdf)

**Comment by Sophiesze** [comment]
I only removed the doublets in the sample which R2>0.9 and skipped for those R2<0.9.

**Comment by rcorces** [comment]
can you show a UMAP colored by (1) Sample and (2) doublet enrichment?

**Comment by Sophiesze** [comment]
Hi, I ran my data according to your suggestion on the QC value. One with the upper bound limitation of the fragment and the other without it to see which one will be better. Both of the plots are posted below. Actually I can't tell which one is better. Cell numbers with upper bound limitations are 91352, the other one is 93273. I still can tell some batch effects after doing harmony. Sorry that I have to hide the sample names on Github. 

Thanks for your help!

**-With the upper bound limitation of log10nf<4.5:**
<img width="448" alt="UB-samples" src="https://user-images.githubusercontent.com/53801318/83618293-d5587400-a5bc-11ea-8254-7eccfb932297.png">
<img width="455" alt="UB-clusters" src="https://user-images.githubusercontent.com/53801318/83618298-d689a100-a5bc-11ea-8bb2-8f5526f60baa.png">


[04-UB-DoubletEnrichment-Umap-0603.pdf](https://github.com/GreenleafLab/ArchR/files/4722845/04-UB-DoubletEnrichment-Umap-0603.pdf)

[5-withUB-Plot-UMAP-Marker-Genes-WO-Imputation.pdf](https://github.com/GreenleafLab/ArchR/files/4722113/5-withUB-Plot-UMAP-Marker-Genes-WO-Imputation.pdf)




**-Without the upper bound:**
<img width="458" alt="without-UB-sample" src="https://user-images.githubusercontent.com/53801318/83618538-28cac200-a5bd-11ea-8b0d-c9345f218c7d.png">
<img width="484" alt="withoutUB-clusters" src="https://user-images.githubusercontent.com/53801318/83618553-2e280c80-a5bd-11ea-81f3-edeb105a79b8.png">


[04-withoutUB-DoubletEnrichment-Umap-0603.pdf](https://github.com/GreenleafLab/ArchR/files/4722844/04-withoutUB-DoubletEnrichment-Umap-0603.pdf)

[5-withoutUB-Plot-UMAP-Marker-Genes-WO-Imputation.pdf](https://github.com/GreenleafLab/ArchR/files/4722126/5-withoutUB-Plot-UMAP-Marker-Genes-WO-Imputation.pdf)

**Comment by rcorces** [comment]
Unfortunately, I do not think this is an ArchR issue. This looks like a problem with your data. Since you had trouble with doublet identification, I'm concerned that this is contributing to your problems. I previously asked for a UMAP colored by the doublet enrichment which I would still encourage you to look at.

We cant really provide solutions for individual user's applications and theres no way for us to know what the mystery clusters are. The advice for identifying clusters or manually defined cell groups is to use marker features or marker gene scores. I'm closing this issue for now. Sorry we could not be of more help.
