### ISSUE TITLE
getGroupBW not normalized

### ISSUE THREAD

**Issue by beccasimmons** [GreenleafLab/ArchR#216]
I have been successful in getting bigwigs using the getGroupBW function, however when I visualise the bigwigs in a browser they do not seem to be normalised. I can see counts so it made met think normalisation has not been applied. The documentation using ?getGroupBW says the default normMethod is "ReadsInTSS" which normalises based on sequencing depth and data quality. Would it be possible to get documentation on the function as well as confirm the default normalisation should be performed? Thanks.

**Comment by jgranja24** [comment]
Hi @beccasimmons,

Sorry for the delay. I found a bug that made it not normalize the bigwigs properly.
Im double checking its functional but the dev branch has the fix.

Best

Jeff

**Comment by beccasimmons** [comment]
Hi Jeff,

I've updated ArchR and rerun the getGroupBW function, and it's definitely changed something but the bigwigs still are not normalised properly. My clusters/samples with more reads and the clusters/samples with less reads are not on the same scale. Would it be possible to get documentation on the function and what exactly is being normalized?

Cheers,
Becca

**Comment by jgranja24** [comment]
Sorry for how delayed this has all been --

The bug has now been fixed in the release branch!

```
#New Release Branch
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())

library(ArchR)

proj <- getTestProject()
getGroupBW(proj, groupBy = "Clusters")

p <- plotBrowserTrack(proj, groupBy = "Clusters", geneSymbol = "CD247", upstream = 100000, downstream = 100000)
plotPDF(p)
```

ArchRBrowser --

<img width="883" alt="Screen Shot 2020-10-27 at 6 00 38 PM" src="https://user-images.githubusercontent.com/25017655/97378094-c2518380-187e-11eb-944d-13a4cf27dd13.png">

Washu --

<img width="1629" alt="Screen Shot 2020-10-27 at 6 00 30 PM" src="https://user-images.githubusercontent.com/25017655/97378107-c7aece00-187e-11eb-8fc8-52849b294e5e.png">

**Comment by jgranja24** [comment]
Closing this issue, feel free to open additional issues!
