### ISSUE TITLE
a little confused about plotTSSEnrichment()

### ISSUE THREAD

**Issue by xuzongren** [GreenleafLab/ArchR#222]
hi,
When i run tutorial examples, "plotTSSEnrichment(ArchRProj = proj1)",I got a diagram that doesn't match the tutorial---Only one sample has a peak,the other samples are almost all flat:
![error](https://user-images.githubusercontent.com/41030907/85494315-fe43b600-b60a-11ea-9705-926f076f7acd.png)
And this the logfile:
[ArchR-plotTSSEnrichment-59342b235e11-Date-2020-06-24_Time-10-57-32.log](https://github.com/GreenleafLab/ArchR/files/4823008/ArchR-plotTSSEnrichment-59342b235e11-Date-2020-06-24_Time-10-57-32.log)
When I run my samples(4 samples),I also get the similar situation----Only one sample has a peak,the other samples are almost all flat,It doesn't matter how many samples I use,Only one sample has a peak. So,I'm not sure what went wrong,I need some help.
Thanks!

**Comment by rcorces** [comment]
I think there is a fundamental problem with your ArchR installation. I see that you are running on Windows which is almost certainly the problem. This is also probably causing your other issue (https://github.com/GreenleafLab/ArchR/issues/217). We have not tested ArchR at all on Windows and are not currently supporting bug fixes related to Windows. We didnt realize this previously because you didnt provide your Session Info in the other issue and no log file was created.

I'd recommend switching to a Unix or MacOS environment.

**Comment by xuzongren** [comment]
@rcorces ,OK,I know what to do,thank you very much for your help.

**Comment by Carota-1** [comment]
@xuzongren ，Hi，Can you present your solution here? Because I have the same issue. thank you!
