### ISSUE TITLE
co-accessibility

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#234]
Hello,

I posted a similar question before, but since I am getting an unexpected result I am opening a new issue.
I would like to find the co-accessibility for each cluster independently. To do so, I basically subsetted my ArchR object into 2 clusters, then for each one of them I added the co-accessibility, and finally visualized it at the browser. I noticed that the result is dramatically different from when I don't do any subsetting. Basically I am not seeing any co-accessibility at the position that I'm interested in when I do the analysis independently on each cluster, but when I do the analysis on everything together I get very densely connected loops at that specific region. I was wondering if you know why this is happening?

This is the function that I use for splitting the ArchR obj into its clusters
```
substot <- function(archr, cluster){
    idxPass <- which(archr$Clusters %in% cluster)
    cellsPass <- archr$cellNames[idxPass]
    return(archr[cellsPass, ])
}
```

**Comment by rcorces** [comment]
I am still struggling with this idea because I dont think that the method of co-accessibility addresses the biological question that you are interested in.

Co-accessibility requires variation - we are measuring the correlation between accessibility at one locus with accessibility at another locus. So, across many different types of cells, you will have variable accessibility, particularly at cell type-specific peaks. This is why you see many co-accessibility interactions without subsetting - because there are cells that have accessibility and cells that dont have accessibility at many different peaks. However, when you subset to a cluster, you are removing nearly all of the variability. So in the subsetted analyses, you are looking for variability within the given cluster which is going to be exceedingly rare.

Does this concept make sense? I'm willing to be proven wrong on this but I don't think that the analytical approach is suited for the biological question.
