### ISSUE TITLE
Error in H5Fopen(file): Unable to open HDF5 file when using subsetArchRProject to create new arrow files

### ISSUE THREAD

**Issue by JohnGenome** [GreenleafLab/ArchR#248]
**Describe the bug**
When I used subsetArchRProject to create new arrow files, a bug arose as in the KI.txt.
```
Copying Arrow Files...
Error in .safelapply(seq_along(inArrows), function(x) { :
Error Found Iteration 1 :
        [1] "Error in H5Fopen(file) : HDF5. File accessibilty. Unable to open file.\n"
        <simpleError in H5Fopen(file): HDF5. File accessibilty. Unable to open file.>
```
[KI.txt](https://github.com/GreenleafLab/ArchR/files/4935510/KI.txt)
If I only use one core, the bug also exists. I would be happy to get your comments on this. Thanks.
```
Copying ArchRProject to new outputDirectory : /asnas/KIR2
Copying Arrow Files...
Error in H5Fopen(file) : HDF5. File accessibilty. Unable to open file.
```

**Session Info**
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /software/biosoft/software/python/anaconda3-python3-2018/lib/libblas.so.3.6.0
LAPACK: /software/biosoft/software/python/anaconda3-python3-2018/lib/liblapack.so.3.6.0

locale:
[1] C

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] ArchR_0.9.5                 magrittr_1.5
 [3] rhdf5_2.28.0                Matrix_1.2-17
 [5] data.table_1.12.6           SummarizedExperiment_1.14.0
 [7] DelayedArray_0.10.0         BiocParallel_1.18.0
 [9] matrixStats_0.55.0          Biobase_2.44.0
[11] GenomicRanges_1.36.0        GenomeInfoDb_1.20.0
[13] IRanges_2.18.1              S4Vectors_0.22.0
[15] BiocGenerics_0.30.0         ggplot2_3.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2                        pillar_1.4.4
 [3] compiler_3.6.1                    XVector_0.24.0
 [5] tools_3.6.1                       bitops_1.0-6
 [7] zlibbioc_1.30.0                   BSgenome_1.52.0
 [9] lifecycle_0.2.0                   tibble_3.0.1
[11] gtable_0.3.0                      lattice_0.20-38
[13] pkgconfig_2.0.3                   rlang_0.4.6
[15] GenomeInfoDbData_1.2.1            stringr_1.4.0
[17] rtracklayer_1.44.2                withr_2.1.2
[19] dplyr_0.8.3                       Biostrings_2.52.0
[21] vctrs_0.2.4                       grid_3.6.1
[23] tidyselect_1.0.0                  glue_1.4.1
[25] R6_2.4.0                          BSgenome.Hsapiens.UCSC.hg19_1.4.0
[27] XML_3.98-1.20                     Rhdf5lib_1.6.0
[29] purrr_0.3.3                       GenomicAlignments_1.20.1
[31] Rsamtools_2.0.0                   scales_1.0.0
[33] ellipsis_0.3.0                    assertthat_0.2.1
[35] colorspace_1.4-1                  stringi_1.4.3
[37] RCurl_1.95-4.12                   lazyeval_0.2.2
[39] munsell_0.5.0                     crayon_1.3.4
[41] Cairo_1.5-10

**Comment by hhvu0102** [comment]
Hi,
I had a similar problem when I tried createArrowFiles(). My input was fragments.tsv.gz file, genome was built for rn6. The attached file is my log file:
[ArchR-createArrows-49244e836d09-Date-2020-07-31_Time-12-16-05.log](https://github.com/GreenleafLab/ArchR/files/5008401/ArchR-createArrows-49244e836d09-Date-2020-07-31_Time-12-16-05.log)
The error that stood out to me was:
> simpleError in H5Fopen(file, native = native): HDF5. File accessibilty. Unable to open file.

I tried processing H5 files in other contexts and it was ok.

I hope you guys can help me solve this problem. Thanks a lot!

**Comment by likelet** [comment]
I encontered  the exact same error  with `addDoubletScores`, here is my command and errors:
```R
ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

doubScores <- addDoubletScores(
  input = ArrowFiles,
  k = 10, #Refers to how many cells near a "pseudo-doublet" to count.
  knnMethod = "UMAP", #Refers to the embedding to use for nearest neighbor search.
  LSIMethod = 1
)
```
and my errors 
```
ArchR logging to : ArchRLogs/ArchR-addDoubletScores-4ce451c38440-Date-2020-08-03_Time-09-52-07.log
If there is an issue, please report to github with logFile!
2020-08-03 09:52:07 : Batch Execution w/ safelapply!, 0 mins elapsed.
Error in H5Fopen(file, "H5F_ACC_RDONLY", native = native) : 
  HDF5. File accessibilty. Unable to open file.
```

My env is : 
```R
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /disk/soft/R-3.5.0/lib/libRblas.so
LAPACK: /disk/soft/R-3.5.0/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] BSgenome_1.50.0             ArchR_0.9.5                 magrittr_1.5                rhdf5_2.26.2                Matrix_1.2-16               data.table_1.12.0          
 [7] SummarizedExperiment_1.12.0 DelayedArray_0.8.0          BiocParallel_1.14.2         matrixStats_0.54.0          Biobase_2.40.0              ggplot2_3.1.0              
[13] rtracklayer_1.42.2          Biostrings_2.48.0           XVector_0.20.0              GenomicRanges_1.34.0        GenomeInfoDb_1.18.2         IRanges_2.16.0             
[19] S4Vectors_0.20.1            BiocGenerics_0.28.0        

loaded via a namespace (and not attached):
  [1] Seurat_3.2.0             Rtsne_0.15               colorspace_1.4-1         deldir_0.1-28            ggridges_0.5.1           rstudioapi_0.9.0         spatstat.data_1.4-3     
  [8] leiden_0.3.1             listenv_0.7.0            npsurv_0.4-0             ggrepel_0.8.0            codetools_0.2-16         splines_3.5.0            lsei_1.2-0              
 [15] polyclip_1.10-0          jsonlite_1.6             Cairo_1.5-12.2           Rsamtools_1.34.1         ica_1.0-2                cluster_2.1.0            png_0.1-7               
 [22] uwot_0.1.8               shiny_1.2.0              sctransform_0.2.0        compiler_3.5.0           httr_1.4.0               assertthat_0.2.1         lazyeval_0.2.2          
 [29] later_0.8.0              htmltools_0.3.6          tools_3.5.0              rsvd_1.0.1               igraph_1.2.4             gtable_0.3.0             glue_1.3.1              
 [36] GenomeInfoDbData_1.1.0   RANN_2.6.1               reshape2_1.4.3           dplyr_0.8.0.1            Rcpp_1.0.1               spatstat_1.64-1          gdata_2.18.0            
 [43] ape_5.3                  nlme_3.1-141             lmtest_0.9-37            stringr_1.4.0            globals_0.12.4           mime_0.6                 miniUI_0.1.1.1          
 [50] irlba_2.3.3              gtools_3.8.1             XML_3.98-1.19            goftest_1.2-2            future_1.14.0            MASS_7.3-51.1            zlibbioc_1.26.0         
 [57] zoo_1.8-4                scales_1.0.0             promises_1.0.1           spatstat.utils_1.17-0    RColorBrewer_1.1-2       reticulate_1.11.1        pbapply_1.4-0           
 [64] gridExtra_2.3            rpart_4.1-15             stringi_1.4.3            caTools_1.17.1.2         rlang_0.4.0              pkgconfig_2.0.2          bitops_1.0-6            
 [71] lattice_0.20-38          Rhdf5lib_1.4.3           ROCR_1.0-7               purrr_0.3.2              tensor_1.5               GenomicAlignments_1.16.0 patchwork_1.0.1         
 [78] htmlwidgets_1.3          cowplot_0.9.4            tidyselect_0.2.5         RcppAnnoy_0.0.13         plyr_1.8.5               R6_2.4.0                 gplots_3.0.1.1          
 [85] withr_2.1.2              pillar_1.3.1             mgcv_1.8-27              fitdistrplus_1.0-14      survival_2.43-3          abind_1.4-5              RCurl_1.95-4.12         
 [92] tibble_2.1.1             future.apply_1.3.0       crayon_1.3.4             KernSmooth_2.23-16       plotly_4.9.0             grid_3.5.0               digest_0.6.18           
 [99] xtable_1.8-3             tidyr_0.8.3              httpuv_1.5.0             munsell_0.5.0            viridisLite_0.3.0       
```

**Comment by vimarin** [comment]
Hi girls and guys, I am rather new in R and ArchR. 
I got same issue when trying to creat the arrow file. 
In practice how did you handle it ? which code line ?

Thanks in advance and nice day

**Comment by rdalbanus** [comment]
+1 to this when running `createArrowFiles` in parallel. No issues when running on a single thread.

**Comment by jgranja24** [comment]
I have been looking into this more see [https://github.com/pachterlab/sleuth/issues/120](https://github.com/pachterlab/sleuth/issues/120). I dont really know how to best diagnose this issue still besides recommending installing more recent versions of rhdf5. The versions I see in this thread are rhdf5_2.28.0, rhdf5_2.30.1, rhdf5_2.26.2. I use rhdf5_2.30.1 currently and we are trying to put together a stable packrat for user download for these type of issues. The current bioconductor version is rhdf5_2.32.4 which may have some stability to these issues. Sorry I am not more helpful at this time.

**Comment by jgranja24** [comment]
For any of you with known corrupt ArrowFiles can you send one of them to [archr.devs@gmail.com ](archr.devs@gmail.com ). I can look into trying to recover these files or something to stabilize this type of issue. Sorry for the troubles

**Comment by jgranja24** [comment]
I think the issue is based on hdf5 file locking. ArchR disables this to speed up these computations in parallel. I wonder if these issues are related to how your operating system handles this file locking procedure. I was able to recapitulate this error but found just disabling file locking (which ArchR tries to do worked).

This is based on this type of error --

`HDF5. File accessibilty. Unable to open file.`

To confirm this is this type of error try --

`h5ls(getArrowFiles(ArchRProj)[1])`

Which should still show the contents indicating this file is not corrupted.

Hope this helps

Jeff

**Comment by jgranja24** [comment]
For createArrowFiles if you disable ie `subThreading = FALSE` I imagine this will allow you to parallelize your creation still. This will just prevent the additional level of parallelization.

**Comment by leeanapeters** [comment]
Hi, I know this issue is closed but I am also experiencing this issue when trying to run GetMarkerFeatures. I disabled subthreading as above but am still getting the error. Any help would be much appreciated!

Thanks

**Comment by rcorces** [comment]
Hi @leeanapeters - Sorry you're having trouble with this. The H5 errors are really hard to track down and we (and many other software developers) are still trying to figure this out. The best I can say is that HDF5 errors are often sporadic and environment specific. If you've tried `threads = 1` and disabling subthreading and that doesnt work, its possible that your HDF5 file got corrupted at some point (no fault of your own). You can try re-running the analysis from a previous project save and see if it resolves. Unfortunately, these errors just are not very reproducible and we have not been able to track down any underlying problems.

**Comment by xiaosuyu1997** [comment]
I guess this issue happens when user try to use ArchR on a HPC cluster system with shared file system (e.g. I meet this question on lustre, which is configured to disable flock for performance issue).
There is one work around in the current release(v1.0.1) for this issue as follows:
- set environment variable: RHDF5_USE_FILE_LOCKING=FALSE
- when createArrowFiles, pass "subThreading = F" argument

I guess there is still some trivial errors in v1.0.1 version, described as follows:
- As the [rhdf5 document](https://rdrr.io/bioc/rhdf5/man/h5fileLocking.html) states, calling h5enableFileLocking() will change the env variable RHDF5_USE_FILE_LOCKING permanently for the current R session. So even user set RHDF5_USE_FILE_LOCKING=FALSE outside, h5enableFileLocking() inside createArrowFiles function will change the wanted behavior. When user do not pass "subThreading = F" to createArrowFiles(), arrow files can be created correctly, but later function calls which want to read or write arrow files will lead to this "HDF5. File accessibilty. Unable to open file." error. For example, I ran into this error when call addDoubletScores.
![image](https://user-images.githubusercontent.com/33937512/109758528-ae4fd100-7c26-11eb-816c-5b5e12351375.png)

Many thanks!

**Comment by rcorces** [comment]
thanks @xiaosuyu1997 - flagging this for @jgranja24

**Comment by tianchen2019** [comment]
> I guess this issue happens when user try to use ArchR on a HPC cluster system with shared file system (e.g. I meet this question on lustre, which is configured to disable flock for performance issue).
> There is one work around in the current release(v1.0.1) for this issue as follows:
> 
> * set environment variable: RHDF5_USE_FILE_LOCKING=FALSE
> * when createArrowFiles, pass "subThreading = F" argument
> 
> I guess there is still some trivial errors in v1.0.1 version, described as follows:
> 
> * As the [rhdf5 document](https://rdrr.io/bioc/rhdf5/man/h5fileLocking.html) states, calling h5enableFileLocking() will change the env variable RHDF5_USE_FILE_LOCKING permanently for the current R session. So even user set RHDF5_USE_FILE_LOCKING=FALSE outside, h5enableFileLocking() inside createArrowFiles function will change the wanted behavior. When user do not pass "subThreading = F" to createArrowFiles(), arrow files can be created correctly, but later function calls which want to read or write arrow files will lead to this "HDF5. File accessibilty. Unable to open file." error. For example, I ran into this error when call addDoubletScores.
>   ![image](https://user-images.githubusercontent.com/33937512/109758528-ae4fd100-7c26-11eb-816c-5b5e12351375.png)
> 
> Many thanks!

Thank you so much! I encountered the same problem and solved it with your solution.

**Comment by kirakornienko** [comment]
Hey everyone, I am so sorry to bother you but as many people had this issue I would like to share the error message and would seek for help as i am also new in computational stuff...
> inputFiles <- c('test'= "/cluster/projects/lupiengroup/Kira/PRO-SPeCT/Patient2/Cellranger-arc_Pat2_Tu1/outs/atac_fragments.tsv.gz")
> inputFiles
                                                                                                      test 
"/cluster/projects/lupiengroup/Kira/PRO-SPeCT/Patient2/Cellranger-arc_Pat2_Tu1/outs/atac_fragments.tsv.gz" 
> export HDF5_USE_FILE_LOCKING=FALSE, RHDF5_USE_FILE_LOCKING=FALSE
Error: unexpected symbol in "export HDF5_USE_FILE_LOCKING"
> HDF5_USE_FILE_LOCKING=FALSE
> HDF5_USE_FILE_LOCKING
[1] FALSE
> addArchRGenome('hg38')
Setting default genome to Hg38.
> addArchRThreads(threads = 1)
Setting default number of Parallel threads to 1.
> ArrowFiles <- createArrowFiles(
+   inputFiles = inputFiles,
+   sampleNames = inputFiles,
+   minTSS = 4, #Dont set this too high because you can always increase later
+   minFrags = 1000,
+   addTileMat = TRUE,
+   addGeneScoreMat = TRUE,
+   subThreading = FALSE
+ )
Using GeneAnnotation set by addArchRGenome(Hg38)!
Using GeneAnnotation set by addArchRGenome(Hg38)!
ArchR logging to : ArchRLogs/ArchR-createArrows-47ed44daa662-Date-2021-12-06_Time-11-46-50.log
If there is an issue, please report to github with logFile!
2021-12-06 11:46:50 : Batch Execution w/ safelapply!, 0 mins elapsed.
2021-12-06 11:46:50 : (/cluster/projects/lupiengroup/Kira/PRO-SPeCT/Patient2/Cellranger-arc_Pat2_Tu1/outs/atac_fragments.tsv.gz : 1 of 1) Reading In Fragments from inputFiles (readMethod = tabix), 0.001 mins elapsed.
2021-12-06 11:46:50 : (/cluster/projects/lupiengroup/Kira/PRO-SPeCT/Patient2/Cellranger-arc_Pat2_Tu1/outs/atac_fragments.tsv.gz : 1 of 1) Tabix Bed To Temporary File, 0.001 mins elapsed.

************************************************************
2021-12-06 11:46:50 : ERROR Found in .tabixToTmp for (/cluster/projects/lupiengroup/Kira/PRO-SPeCT/Patient2/Cellranger-arc_Pat2_Tu1/outs/atac_fragments.tsv.gz : 1 of 1) 
LogFile = ArchRLogs/ArchR-createArrows-47ed44daa662-Date-2021-12-06_Time-11-46-50.log

<simpleError in H5Fcreate(file): HDF5. File accessibility. Unable to open file.>

************************************************************

2021-12-06 11:46:50 : createArrowFiles has encountered an error, checking if any ArrowFiles completed..
ArchR logging successful to : ArchRLogs/ArchR-createArrows-47ed44daa662-Date-2021-12-06_Time-11-46-50.log

if someone has a solution i would appreciate it! thank you

**Comment by rcorces** [comment]
@xiaosuyu1997 - I know that your solution is about a year old and I'm sorry that we havent implemented it yet. I'm trying to tidy up the current development branch (`release_1.0.2`) to create a stable release and I would like to adequately address this.

Could you clarify your solution?

From what I understand, the primary problem is that ArchR defaults to using `h5disableFileLocking()` and `h5enableFileLocking()` which cause problems on certain systems. In `createArrowFiles()` this can be avoided by setting `subThreading = FALSE` in the params. But in other functions, `h5disableFileLocking()` and `h5enableFileLocking()` are used without an option to set `subThreading = FALSE`.

A solution would be to set the default value for `subThreading` to be `FALSE` and to add the `subThreading` param to any function that would potentially call `h5disableFileLocking()` and `h5enableFileLocking()` and prevent users from calling these functions if `subThreading = FALSE`. Does that sound right?

Would we need to additionally set default values (`FALSE`) for the environment variables `HDF5_USE_FILE_LOCKING` and `RHDF5_USE_FILE_LOCKING`? This seems like it would also be important given that the default is to use file locking.

**Comment by wfma** [comment]
Sorry to chime in but i am also having this issue intermittently while running ArchR in Dockerized RStudio (Rocker Project). The issue seems to go away if I completely restart the R session or remove the loaded R project.

**Comment by xiaosuyu1997** [comment]
Sorry for late reply.

> A solution would be to set the default value for subThreading to be FALSE and to add the subThreading param to any function that would potentially call h5disableFileLocking() and h5enableFileLocking() and prevent users from calling these functions if subThreading = FALSE. Does that sound right?

I think maybe cases where subThreading has to be FALSE is rare (default to TRUE maybe better for effeciency?). The most important question maybe the consistency of lock-use in one run (environment variable -> createArrowFiles -> later function calls use these ArrowFiles), changing in midtime may not be a good idea. This shall be warned in the document, especially for Network File System users who may run into these problems. 
Checking the environment variable (need HDF5_USE_FILE_LOCKING=TRUE + RHDF5_USE_FILE_LOCKING=TRUE + subThreading=TRUE to enable file locking) maybe a better idea, cause maybe we want the superior behavior of ENV vars.

**Comment by BeyondTheProof** [comment]
I've had the same error when trying to call `addGroupCoverages`. I've managed to resolve this error by setting `threads=1`.

**Comment by VDD58** [comment]
Hi, 
I also have the same problem if HDF5, I do use human genome. 
I have tried as previously suggested to start from an earlier saved project, do threads =1 and or subthreads=False. 
The problem is that i still get the same error message which is the following: 
Error in h5ls(ArrowFile): HDF5. Object header. Can't get value.
Traceback:

1. addGeneIntegrationMatrix(ArchRProj = proj2.1_integr, useMatrix = "GeneScoreMatrix", 
 .     matrixName = "GeneIntegrationMatrix", reducedDims = "IterativeLSI", 
 .     seRNA = seRNA, addToArrow = TRUE, force = TRUE, groupRNA = "differentiation", 
 .     nameCell = "predictedCell", nameGroup = "predictedGroup", 
 .     nameScore = "predictedScore", threads = 1)
2. .safelapply(seq_along(allSamples), function(y) {
 .     sample <- allSamples[y]
 .     prefix <- sprintf("%s (%s of %s)", sample, y, length(ArrowFiles))
 .     .logDiffTime(sprintf("%s Getting GeneIntegrationMatrix From TempFiles!", 
 .         prefix), tstart, verbose = verbose, logFile = logFile)
 .     sampleIF <- lapply(seq_along(h5list), function(x) {
 .         if (any(h5list[[x]]$group == paste0("/", sample))) {
 .             integrationFiles[x]
 .         }
 .         else {
 .             NULL
 .         }
 .     }) %>% unlist
 .     sampleMat <- lapply(seq_along(sampleIF), function(x) {
 .         cellNames <- .h5read(sampleIF[x], paste0(sample, "/cellNames"))
 .         mat <- sparseMatrix(i = .h5read(sampleIF[x], paste0(sample, 
 .             "/i"))[, 1], j = as.vector(Rle(.h5read(sampleIF[x], 
 .             paste0(sample, "/jValues"))[, 1], .h5read(sampleIF[x], 
 .             paste0(sample, "/jLengths"))[, 1])), x = .h5read(sampleIF[x], 
 .             paste0(sample, "/x"))[, 1], dims = c(nrow(featureDF), 
 .             length(cellNames)))
 .         colnames(mat) <- cellNames
 .         mat
 .     }) %>% Reduce("cbind", .)
 .     sampleMat@x <- exp(sampleMat@x) - 1
 .     sampleMat <- .normalizeCols(sampleMat, scaleTo = scaleTo)
 .     sampleMat <- drop0(sampleMat)
 .     rownames(sampleMat) <- paste0(featureDF$name)
 .     sampleMat <- sampleMat[, ArchRProj$cellNames[BiocGenerics::which(ArchRProj$Sample == 
 .         sample)], drop = FALSE]
 .     o <- .createArrowGroup(ArrowFile = ArrowFiles[sample], group = matrixName, 
 .         force = force)
 .     o <- .initializeMat(ArrowFile = ArrowFiles[sample], Group = matrixName, 
 .         Class = "double", Units = "NormCounts", cellNames = colnames(sampleMat), 
 .         params = dfParams, featureDF = featureDF, force = force)
 .     o <- h5write(obj = dfAll[colnames(sampleMat), "predictionScore"], 
 .         file = ArrowFiles[sample], name = paste0(matrixName, 
 .             "/Info/predictionScore"))
 .     o <- h5write(obj = dfAll[colnames(sampleMat), "predictedGroup"], 
 .         file = ArrowFiles[sample], name = paste0(matrixName, 
 .             "/Info/predictedGroup"))
 .     o <- h5write(obj = dfAll[colnames(sampleMat), "predictedCell"], 
 .         file = ArrowFiles[sample], name = paste0(matrixName, 
 .             "/Info/predictedCell"))
 .     .logDiffTime(sprintf("%s Adding GeneIntegrationMatrix to ArrowFile!", 
 .         prefix), tstart, verbose = verbose, logFile = logFile)
 .     for (z in seq_along(allChr)) {
 .         chrz <- allChr[z]
 .         .logDiffTime(sprintf("Adding GeneIntegrationMatrix to %s for Chr (%s of %s)!", 
 .             sample, z, length(allChr)), tstart, verbose = FALSE, 
 .             logFile = logFile)
 .         idz <- BiocGenerics::which(featureDF$seqnames %bcin% 
 .             chrz)
 .         matz <- sampleMat[idz, , drop = FALSE]
 .         stopifnot(identical(paste0(featureDF$name[idz]), paste0(rownames(matz))))
 .         o <- .addMatToArrow(mat = matz, ArrowFile = ArrowFiles[sample], 
 .             Group = paste0(matrixName, "/", chrz), binarize = FALSE, 
 .             addColSums = TRUE, addRowSums = TRUE, addRowVarsLog2 = TRUE, 
 .             logFile = logFile)
 .         rm(matz)
 .         if (z%%3 == 0 | z == length(allChr)) {
 .             gc()
 .         }
 .     }
 .     0
 . }, threads = threads)
3. lapply(...)
4. FUN(X[[i]], ...)
5. .createArrowGroup(ArrowFile = ArrowFiles[sample], group = matrixName, 
 .     force = force)
6. .summarizeArrowContent(ArrowFile)
7. h5ls(ArrowFile)


ArchR-addGeneIntegrationMatrix-19443462eecb-Date-2022-07-05_Time-19-32-06.log

I am definitely running out of ideas so if anybody has a suggestion i would be glad.

**Comment by rcorces** [comment]
@VDD58 - I dont have a solution for your problem but we are hoping that an upcoming release will fix many of these HDF5 problems. That being said, I dont think the error you are reporting is the same as what is discussed in this issue post.

Also, in the future, please upload you log file rather than pasting the full text into the issue.

**Comment by VDD58** [comment]
Thank you so much for responding!

**Comment by rcorces** [comment]
I believe this has now been addressed properly on the `dev` branch via https://github.com/GreenleafLab/ArchR/commit/55f09239cd938552d42582ee046c66189cd121f2#diff-bab2afba66a9980d18aaaa80450eaeff5c80a12eb8a943c0680d7b71b06b7e5e

There is a more stable way of handling file locking that will be implemented in `release_1.0.3` and described in an upcoming release of the manual.

**Comment by mdanb** [comment]
@rcorces I installed the version in `dev`, I still get the same error

**Comment by rcorces** [comment]
@mdanb - I'll need more information to actually help. The `dev` version includes a new way of preventing HDF5 accessibility errors. You would likely need to disable subthreading by running `addArchRLocking(locking = TRUE)` prior to running `createArrowFiles()`. In the future, please always upload your ArchR log file when posting to GitHub.

**Comment by mdanb** [comment]
@rcorces I'm good. It turns out it was because my `sampleNames` had a `/` which threw things off

**Comment by jgarces02** [comment]
Hi, none of the above things worked for me. The only thing that let me continue was to set `copyArrows = F`

`archro <- ArchRProject(arrowfiles, outputDirectory = "archr_test", thread = 1, copyArrows = FALSE)`
