### ISSUE TITLE
Possible generation of pseudo-bulk BAM files?

### ISSUE THREAD

**Issue by hugokitano** [GreenleafLab/ArchR#278]
One thing that's been very helpful is the generation of bigwig visualization files with `plotBrowserTrack.` Using this, I've been able to use the single cell ATAC-seq data as a kind of pseudo-bulk ATAC-seq. I was wondering if there was a way you know of to create a BAM file in the same kind of way to do peak-calling and other analyses. Thanks!

**Comment by rcorces** [comment]
There is no way to get a true BAM file (containing sequence) because this information is discarded during fragment file creation. The approved way to do what you want would be to create a BED file from a fragment file and use that to do your downstream analyses. Otherwise, if you really want a BAM file, you would have to take the cellular barcodes from ArchR and extract these from the BAM file yourself.

You can extract specific cells from an Arrow file using `getFragmentsFromArrow()`. If you want to create a single fragment file from cells from multiple Arrow files, you would merge those fragment files after extraction.
