### ISSUE TITLE
How to export peak accessibility matrix?

### ISSUE THREAD

**Issue by smorabit** [GreenleafLab/ArchR#283]
Hello, 

I am trying to export the peaks by cells accessibility matrix for external use, but when I use `getMatrixFromProject` the number of cells is much fewer than the number of cells in my ArchR project. I used the following code to call peaks and extract the matrix, and I included the log file for my `getMatrixFromProject` call.

```

proj <- addGroupCoverages(ArchRProj = proj, groupBy = "Clusters", force=TRUE)
pathToMacs2 <- findMacs2()
proj <- addReproduciblePeakSet(
    ArchRProj = proj,
    pathToMacs2 = pathToMacs2,
    groupBy = "Clusters"
)
proj <- addPeakMatrix(proj)
test <- getMatrixFromProject(proj, useMatrix='PeakMatrix')

```

The `test` SummarizedExperiment object has about ~20k fewer cells than `proj`. I am not sure if this is a bug or if this is by design.

One other thing I noticed is that while running `addReproduciblePeakSet`, a table is printed out at the beginning like this:

|       | Group | nCells | nCellsUsed | nReplicates | nMin | nMax | maxPeaks |
|-------|-------|--------|------------|-------------|------|------|----------|
| ASC.a | ASC.a | 5602   | 2265       | 5           | 370  | 500  | 150000   |
| ASC.b | ASC.b | 3371   | 1703       | 5           | 287  | 404  | 150000   |
| ASC.c | ASC.c | 3236   | 1607       | 5           | 242  | 414  | 150000   |
| ASC.d | ASC.d | 1514   | 578        | 5           | 96   | 152  | 150000   |

It appears that not all cells are being used to call peaks, based on the `nCellsUsed` column in this table, could this be why `getMatrixFromProject` doesn't return all cells? Additionally, I tried using `getMatrixFromProject` to extract the `GeneScoreMatrix`, and I was able to get a matrix for all cells in the ArchR project this way.

Any help would be greatly appreciated!

[ArchR-getMatrixFromProject-43635feabc84-Date-2020-08-13_Time-11-12-50.log](https://github.com/GreenleafLab/ArchR/files/5070893/ArchR-getMatrixFromProject-43635feabc84-Date-2020-08-13_Time-11-12-50.log)

**Comment by smorabit** [comment]
The plot thickens...

I re-started my analysis from scratch to see where this problem started, and now I suspect that the issue arises from how I created the arrow files. Before when creating arrow files I opted not to remove filtered cells so I could apply my own filtering after the fact (code shown below).

```
ArrowFiles <- createArrowFiles(
  inputFiles = sample_files,
  sampleNames = sample_names,
  filterTSS = 4, 
  filterFrags = 1000,
  removeFilteredCells = FALSE,
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)
```

I changed this code to this:

```
ArrowFiles <- createArrowFiles(
  inputFiles = sample_files,
  sampleNames = sample_names,
  filterTSS = 1, 
  filterFrags = 100,
  removeFilteredCells = TRUE,
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)
```

In both cases I am filtering out additional cells using the `subsetCells` function. After LSI and clustering, I am calling peaks the same way in both cases as shown in my post above. When I call peaks on the ArchR project that I did not remove filtered cells, and then try to extract the peak accessibility matrix, I get the expected shape including all cells in the ArchR project. Thus I suspect something under the hood is going wrong when using the `removeFilteredCells = FALSE` option in `createArrowFiles`. From my end I have no idea why this would be the solution since I am using the exact same cells in both cases. 

Anyways I hope this might help identify some underlying issues with the createArrowFiles function!

**Comment by rcorces** [comment]
Thanks. This is helpful. We will look into this. We don't often use `removeFilteredCells = FALSE` so its possible that there is something amiss.

**Comment by jgranja24** [comment]
Hmmm I wonder if its best to force removeFilteredCells.... @rcorces what do you think? This bug is very bizzare.

**Comment by rcorces** [comment]
Without fully understanding whats going on under the hood - I think its reasonable to get rid of the `removeFilteredCells` option and just force removal. If users dont want to remove those cells, then they can set the cutoffs to whatever they want. If they later want to remove cells based on QC metrics, they could do so by using `subsetArchRProject` for example.

I think in an ideal world `removeFilteredCells` would exist and work appropriately but if it is difficult or complicated, I think it is not a necessary feature.

**Comment by jgranja24** [comment]
I removed the param `removedFilteredCells` in the release branch to avoid this issue.

**Comment by jgranja24** [comment]
Closing this issue, thanks for the report and feel free to open new issues!

**Comment by leoTiez** [comment]
Firstly, thank you very much for your great work and making it publicly available. That's highly appreciated.
I don't want to necessarily re-open this and it's neither really a bug, but I found a behaviour that I think is related to this issue and might need attention. So I let you decide how to classify this :)

I have a data set with 3 replicates which needed some additional replicate-specific filtering after initial loading (i.e. after creating the arrow files). I set for cells that don't pass my customised quality control (QC) a flag. I re-use the `PassQC` column that is created by `ArchR`. All cells where the flag is set are removed **prior** to peak calling. 

Now, I want to create an h5ad data structure based on the `.arrow` files, so that I can use it with other libraries and programming languages (e.g. scanpy). When I extract the `GeneScoreMatrix` from the `.arrow` files, everything works well (at least no error is thrown). However, when I want to extract the `PeakMatrix`, I've got less rows in my matrix than in my `obs` column (ie. the number of single cells differ). After digging deeper I realised that the peak calling was obviously performed on a reduced cell set (i.e. only cells that passed QC). However, the `obs` column still contains all cells.  Moreover, even though the project is successfully updated after removing low quality cells, the `.arrow` files still contain all cells (which is why the `GeneScoreMatrix` doesn't throw an error). When investigating the `PassQC` flags, all cells are still marked with having passed the QC thresholds (i.e. `PassQC = 1`). This similarly happens when using `getMatrixFromArrow` in `R` directly: the `GeneScoreMatrix` and the `PeakMatrix` have different number of cells. They need to be matched with their cell ID to filter the `GeneScoreMatrix`. Taken together, when considering the `.arrow` files, the `GeneScoreMatrix` contains all cells (even cells that were manually removed after initial loading), whereas `PeakMatrix` contains only cells that were included in the ArchR project when peak calling was performed.

I've the feeling that the `.arrow` files should be to some extend kept in sync with the project in this case. Personally, I think either there's a way to manipulate the equivalent of the `.obs` column in the arrow files (for example `PassQC` is updated in the arrow files when `saveArchRProject` is called) so retrieved matrices can be made comparable after retrieval from the `.arrow` files. Or the `.arrow` files are equally subset when cells are removed in the ArchR project.

What do you think?

PS: I use R 4.3.1 and I tried it on two Apple computers, one with Quad-Core Intel Core i7 x86_64 architecture and the other one with Apple Silicon Apple M2.

**Comment by leoTiez** [comment]
OK, for people that run into the same issue: there's the `dropCells` parameter for the `saveArchRProject` function which is per default set to `FALSE`. Setting it to `TRUE` should resolve the mismatch.
