### ISSUE TITLE
Extra parameters for FindTransferAnchors in addGeneIntegrationMatrix 

### ISSUE THREAD

**Issue by RegnerM2015** [GreenleafLab/ArchR#316]
Hi @jgranja24 and @rcorces , 

I have a question regarding the specific parameters that are involved in Seurat's `FindTransferAnchors` and `TransferData` when using the `addGeneIntegrationMatrix` function. 

I would like to perform the RNA/ATAC integration using 1:50 nPCs (RNA) and 1:50 LSI dims (ATAC). How would I about doing this in ArchR? I think I can set the number of LSI dims using the transferParams argument: 

`addGeneIntegrationMatrix(transferParams = list(dims = 1:50),...)`

However, how would I specific the number of PCs for the RNA reduction? By default, Seurat FindTransferAnchors uses 1:30 nPCs. I would like to change this to 1:50. What is the best route moving forward? 

Thanks!

**Comment by jgranja24** [comment]
I believe first you need to set the dims in `addIterativeLSI` and then use that as input. I dont think the scRNA dims can be tuned for Seurat?

**Comment by jgranja24** [comment]
I also have now added the parameters to `addGeneIntegrationMatrix` for the scATAC LSI data -

```
  dimsToUse = 1:30,
  scaleDims = NULL,
  corCutOff = 0.75,
```

**Comment by jgranja24** [comment]
First install the new release branch

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.0", repos = BiocManager::repositories())
`

For the scRNA dimensions i believe you should use

dimsToUse - scATAC
dims, nPCs - scRNA

`addGeneIntegrationMatrix(dimsToUse=1:50, transferParams = list(dims = 1:50), nPcs = 50, dims = 1:50, ...)
`

This is because `#' @param ... Additional params to be added to `Seurat::FindTransferAnchors``

SEE here -
[https://rdrr.io/cran/Seurat/man/FindTransferAnchors.html](https://rdrr.io/cran/Seurat/man/FindTransferAnchors.html)

npcs | Number of PCs to compute on reference. If null, then use an existing PCA structure in the reference object
dims | Which dimensions to use from the reduction to specify the neighbor search space

**Comment by jgranja24** [comment]
I am closing this issue, if you have any more issues please feel free to open a new issue!
