### ISSUE TITLE
ArchR object as Signac object 

### ISSUE THREAD

**Issue by ankushs0128** [GreenleafLab/ArchR#349]
I am looking for an option to convert ArchR object to Seurat object for iterating resolution for cluster detection.  Is it possible to convert ArchR object to Seurat object? I tried using e.g. 
x <- as.Seurat(x )
Error in UseMethod(generic = "as.Seurat", object = x) : 
  no applicable method for 'as.Seurat' applied to an object of class "ArchRProject"

Thanks in advance

**Comment by rcorces** [comment]
I dont believe this feature request makes sense. Seurat is not designed to use ATAC-seq data and you can tweak parameters for cluster identification from within ArchR.  See the function definition:
https://www.archrproject.com/reference/addClusters.html
Especially the `...` argument which allows you to pass additional arguments to `Seurat::FindClusters()`. I'm closing this but if you feel that this does not adequately address your needs, please post a reply here.

**Comment by ankushs0128** [comment]
Apologies for the incorrect info. I meant Signac here. I would like to identify resolutions for the identification of clusters using scClustviz.  Hope it makes sense!

Thanks in advance

**Comment by rcorces** [comment]
Sounds like a great feature request for the scClustViz team :) 

I don't think this is currently supported and I'm not familiar with scClustViz. From a cursory glance, it isnt clear whether there are any assumptions made that would make it unwise to use such a tool for scATAC-seq data.  There are a lot of reasons why we wouldnt want to implement something that converts ArchR format to other formats - mainly because we would then have to support any changes made to those other formats.

I'll let @jgranja24 give you a more informed answer.

**Comment by jgranja24** [comment]
Hi @ankushs0128,

If you use `getMatrixFromProject` it returns a summarized experiment. This can be converted to a Seurat/Signac object with `as.Seurat`. You can then add your reduced dimensions as follows

```

library(ArchR)
library(Seurat)
library(SingleCellExperiment)

se <- getMatrixFromProject(projHeme5, "PeakMatrix")
se <- as(se, "SingleCellExperiment")
names(assays(se)) <- "counts"
rownames(se) <- paste0(seqnames(se), ":", start(se),"-",end(se))
seuratObj <- as.Seurat(se, data = NULL)
rD <- getReducedDims(projHeme5)
seuratObj[["iterativeLSI"]] <- CreateDimReducObject(embeddings = rD, key = "ISLI_", assay = DefaultAssay(seuratObj))
seuratObj

```

Best

Jeff

**Comment by ankushs0128** [comment]
Thanks,  i will check it out
