### ISSUE TITLE
Draw heatmap with only user-defined genes

### ISSUE THREAD

**Issue by cschmidl** [GreenleafLab/ArchR#437]
Dear Jeffrey and Ryan,

I would like to create a heatmap that only displays user-defined gene activities over groups (even if they are not marker genes)? This would be very handy to show literature-defined geneactivities over clusters.

Is this possible?

Thanks a lot!
Christian

**Comment by rcorces** [comment]
The output of the `getMarkerFeatures()` function is a `Summarized Experiment`. You should be able to manipulate this just like any summarized experiment object.  I think something like this would be fine:
```
se <- getMarkerFeatures(ArchRProj = projTest, useMatrix = "GeneScoreMatrix")
subsetSE <- se[which(rowData(se)$name %in% c("EVI5","RPF1","AK5")),]
plotMarkerHeatmap(seMarker = subsetSE)
```

That being said, I think this would be a useful feature to implement within `plotMarkerHeatmap()`

**Comment by cschmidl** [comment]
Sorry, I did not realize that also non-markers were in this Summarized Experiment and I had to simply put the FDR very high to also plot the non-markers!

**Comment by rcorces** [comment]
Correct. This is probably why this feature does not exist within `plotMarkerHeatmap()` because there is no way to guarantee that the genes exist within the SE. The alternative to the previous solution I suggested would be to use `getMatrixFromProject()` and plot your heatmap outside of ArchR - this avoids having to use `getMarkerFeatures()` and lower the statistical cutoffs arbitrarily.

I'm going to close but feel free to add additional thoughts.
