### ISSUE TITLE
addHarmony, addCluster or addUMAP:: how to set dimsToUse?

### ISSUE THREAD

**Issue by coffeeCowLu** [GreenleafLab/ArchR#439]
how to set dimsToUse in the three functions?

dimsToUse=1:30 ?    or    dimsToUse=2:30?
(Signac: in LSI dims, the first dim may be sequence depth noise, it is recommended to use dims=2:30)

I have tested the 1:30 and 2:30 , i found 
1:30:: The cell clustering was somewhat trailing without harmony,  and the heterogeneity was higher after harmony was added.

2:30:: The clusters of cells are clearly defined without harmony, and the clusters are a little bit trailing after harmony.

DimToUse =2:30 with harmony works better. I'm not sure if this is true.

**Comment by jgranja24** [comment]
Hi @coffeeCowLu ArchR correlates the dims to the sequencing depth automatically and filters dims abs(correlated) > 0.75. However, in some cases the 1st dimension may be correlated to other technical noise not depth related. In general ArchR defaults are reasonable and dont need to be removed. If you think the results make more sense if you remove the first dimension thats totally reasonable. Biological intuition is important here to evaluate what you expect and if removing that dimensions steers you closer to your expectation than that is fine. In most cases it doesnt have a strong effect because of the iterative LSI method (ArchR) vs LSI (Signac). 

I hope that makes sense.

Jeff

**Comment by coffeeCowLu** [comment]
@jgranja24 Thank you for your prompt reply.
