### ISSUE TITLE
dimension using scaleDims

### ISSUE THREAD

**Issue by erikla** [GreenleafLab/ArchR#447]
This relates to question [323](https://github.com/GreenleafLab/ArchR/issues/323)

Does the corCutOff argument that limits the correlation of depth and dimension depend on whether scaleDims was set to true or not?
In my own data, I see a correlation (>.9) between the first dimension and depth in ..[[reducedDims]]corToDepth$none, but significantly less (.1) in [[reducedDims]]$corToDepth$scaled.  By default, the scaled metrics are used.  Can I filter this dimension using both corCutOff and scaleDims in addClusters or addUmap?

**Comment by rcorces** [comment]
`corCutOff` and `scaleDims` are quite different and are independent (as far as i know).
`corCutOff` will exclude dimensions that are highly correlated to sequencing depth.
`scaleDims` is used to prevent a single dimension from dominating but that dimension might not be at all related to sequencing depth. But `scaleDims` does not "filter" any dimensions.
I'm not sure if this answers your question.

**Comment by erikla** [comment]
Thank you for your response and the nice ArchR framework.
I ask because it seems getReducedDims function uses either corToDepth$scaled or corToDepth$none to exclude dimensions based on corCutOff.
For example:
>   matLSI <- getReducedDims(ArchRProj = ArchRProj,
+                            reducedDims = 'IterativeLSI',
+                            scaleDims = F,
+                            corCutOff = 0.75)
Filtering 1 dims correlated > 0.75 to log10(depth + 1)
>   dim(matLSI)
[1] 14806    29
>   matLSI2 <- getReducedDims(ArchRProj = ArchRProj,
+                            reducedDims = 'IterativeLSI',
+                            corCutOff = 0.75)
>   dim(matLSI2)
[1] 14806    30

**Comment by rcorces** [comment]
Hmmm. I understand your question now. I'm going to let @jgranja24 reply to this.

**Comment by jgranja24** [comment]
When ArchR creates a reduced dimensionality LSI it the correlates the components to sequencing depth with and without scaling. By default ArchR uses `scaleDims = TRUE` and thus uses the correlations associated. I would only used the corresponding correlations and not the scaled values. However, you can always use `dimsToUse` if you want to filter this.

Best

Jeff

**Comment by erikla** [comment]
Jeff, thank you for your response.  If I understood correctly calling getReducedSims() uses scaleDims = TRUE by default, and the returned dimensions are based on depth-correlation vector found in proj@reducedDims$IterativeLSI$corToDepth$scaled.  Does the proj@reducedDims$IterativeLSI$corToDepth$none vector contain the non-scaled depth correlations?  If so, I think this is more intuitive and can set dimsToUse to filter based on $none.

Thanks.

**Comment by dagarfield** [comment]
Hi all,

Thanks for the excellent thread and program -- I think I follow from the above, but I want to make sure that I understand the behavior. 

As is typically, the first component of my SVD is strongly correlated with read depth -- well above the threshold for removal set as default for corCutOff. The corresponding correlation for the scaled values, in contrasts, is well below this. 

Thus, if I push ahead using default settings, my downstream analyses will use scaled components and, in this case, all of the components (since no correlation with read depth is > .2 or so). But if I set scaleDims to False, I will end up using 2:30 (as appropriate) given that the first component is so strongly correlated with read depth. 

My confusion here stems from the fact that scaled or not, would it not make sense to drop the first component if its (unscaled) values are so strongly correlated with read depth?

--DG
