### ISSUE TITLE
parameters in addIterativeLSI

### ISSUE THREAD

**Issue by bioinfo-sc** [GreenleafLab/ArchR#457]
Hi,

I am a new user to ArchR to analyze my scATAC-seq data. This is a great tool.
I have one question regarding the parameters in addIterativeLSI.

I checked the default parameters for dimsToUse is 1:30. I was trying to adjust the number of parameters. Is there any similar way to check the appropriate parameters to use, like elbow plot in Seurat?

Also, another parameter is iterations in the addIterativeLSI? Could you please help to suggest some best way to select the best addIterativeLSI parameter?

Thank you very much!

**Comment by jgranja24** [comment]
Hi @bioinfo-sc, 

At the moment there isnt any functionality for this. General rule of thumb is that 1:30 covers majority of the variance and if you want to further minimize "technical variance" you can lower this. Sorry that its not a perfect science because the variance from LSI is different than scRNA PCA. We covered this info in the ArchR book which you can reference! Basically 2 total iterations covers 95% plus of situations and sometimes 3 or more is useful.

See -[https://www.archrproject.com/bookdown/iterative-latent-semantic-indexing-lsi.html]( https://www.archrproject.com/bookdown/iterative-latent-semantic-indexing-lsi.html)
