### ISSUE TITLE
plotEmbedding with 2 markers on same UMAP?

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#461]
Is there a way to plot 2 markers on the same UMAP embedding ( to see the degree of overlap)?

Thanks!

**Comment by rcorces** [comment]
This is not currently possible but I know the feature that you are referring to. I think this is a good idea.

**Comment by sylestiel** [comment]
Looking forward to its implementation soon.

**Comment by rcorces** [comment]
I'm going to leave this open as a reminder for this feature request

**Comment by jgranja24** [comment]
This feature doesnt make sense to me. I also dont see anyway I can implement this. My recommendation is just to make 2 UMAP plots and plot them side by side with `ggAlignPlots(p1,p2,type="h")`. There isnt really a chance I can make this possible because plotEmbedding takes in a list of features and plots them iteratively. 

Hope that helps

Jeff
