### ISSUE TITLE
IterativeLSI using customized sets of genomic loci

### ISSUE THREAD

**Issue by MagpiePKU** [GreenleafLab/ArchR#464]
**Describe the problem that your feature request would address.**
The current addIterativeLSI function only recognizes TileMatrix and PeakMatrix (by default). We noticed strong variability of some unwanted genomic regions might contribute a majority of cell-to-cell variability and it is very  desirable to  remove them from  

**Describe the solution you'd like**
I would like to suggest a function to use an arbitrary GRanges as region-of-analysis for iterative LSI. 

**Describe alternatives you've considered**
 Otherwise, we could also give an arbitrary black-list for masking certain genomic regions for iterative LSI. 

**Additional context**
We tried filtering against the regions like using a customized GRanges object in addFeatureMatrix and use the new FeatureMatrix to perform addIterativeLSI (modified to accept other matrix names) but it did not work.

**Comment by rcorces** [comment]
I think this is better handled on the user side rather than implementing Iterative LSI with arbitrary feature sets.
Presumably if you have regions that you explicitly want to ignore, you would have two regions:

1) You know these regions a priori so you add them to your blacklist and create a custom genome annotation
2) You identify these regions after clustering and calling peaks. You can remove these regions from your peak set using standard GRanges manipulations and then add this modified GRanges object as the peak set for your project using `addPeakSet()`.

The second solution sounds like what you tried but it uses the `PeakMatrix` instead.

I'm going to close this but if you feel like the solution provided does not address your issue, just comment again and I will re-open.
