### ISSUE TITLE
maybe bugs with arrow file generations?

### ISSUE THREAD

**Issue by yding9** [GreenleafLab/ArchR#472]
Dear authors,

I am trying to use ArchR for 10X Multiome analysis but I meet some problems which I don't know how to solve. I guess this problem may also exist in the scATAC-seq analysis but I didn't notice it before.

I use the atac_fragments.tsv.gz files as input. In order to find all cell barcodes defined by cellranger-arc in arrow files, I define cutoff values to very small numbers (minimal number of fragments = 1, minimal TSS enrichment = 0). By doing this I get 1,395,741 barcodes in the ArchR project for these two libraries together. There are a total of 1,402,535 unique barcodes in these two atac_fragments.tsv.gz files. So there are 1,402,535 - 1,395,741 = 6,794 barcodes are excluded in the arrow files.

When I intersect those 1,395,741 barcodes in the ArchR object with 10X cell barcodes I only get 17,550 cell barcodes. However, I’m expecting 10,801+13,445 = 24,246 cell barcodes (as reported in cellranger-arc outputs). There are 6,746 missing cell barcodes. Do you have any idea where those excluded (6,794) or missing (6,746) barcodes go? Can you advise me on the right method to find all cell barcodes when generating arrow files?

Thanks a lot for your help!

**Comment by rcorces** [comment]
I can't say that I know why you would want to do this but I'll try to help. My intuition is that you should do whatever it is you want outside of ArchR because including droplets with only a few fragments is not something that this tool was benchmarked to do in terms of downstream analyses.

That being said, there are a couple of parameters that are used for creating Arrow files.

> So there are 1,402,535 - 1,395,741 = 6,794 barcodes are excluded in the arrow files.

Maybe this is because of the `minFrags` and `maxFrags` arguments? Perhaps you are losing fragments this way?

Alternatively, have you tried changing `removeFilteredCells` to be `FALSE`?

I would say that if you want additional help on this, you should recapitulate what you are seeing with the tutorial data and provide the exact code so that we can better help. I do not anticipate this being something specific to the multiome but if you cannot recapitulate this with the tutorial scATAC-only data, let us know.

**Comment by yding9** [comment]
Thank you so much for your insightful suggestion! Actually, this issue comes from the maxFrags argument. The default maxFrags = 10e5 but more than 6,000 barcodes have more than 10e5 fragments. After setting maxFrags equal to 10e7 I'm able to recover all cell barcodes defined by cellranger-arc.

Thanks again for this wonderful tool! Looking forward to more multimodal updates!
