### ISSUE TITLE
Impute the Peak-count matrix

### ISSUE THREAD

**Issue by SunKeYong** [GreenleafLab/ArchR#518]
Is it possible to Impute the Peak-count matrix?  As we all know, the analysis of scATAC-seq data is particularly challenging because sparsity is intrinsic to these assays. Many tools, such as FITs (https://reggenlab.github.io/FITs/), have been developed to recover original signals from highly sparse and noisy scATAC-seq profiles. So, I suggest that you can integrate these tools into ArchR, which will enhance the performance of  ArchR in the downstream analysis.

**Comment by rcorces** [comment]
Thanks for the suggestion. I think there is a general interest to make ArchR more easily integrated with other tools and to make it easier to pull data out of ArchR. We're working on it but also trying to prioritize some other things at the moment so this will just take time. Appreciate your patience!

**Comment by jgranja24** [comment]
Hi @SunKeYong, technically you can impute the Peak-count matrix with MAGIC as is as well I am pretty sure. Just use them in plotEmbedding. I am not sure that we will directly support imputation for anything but visualization because they can be misleading. We will look more into this as these tools are developed!
