### ISSUE TITLE
Subclustering strategy

### ISSUE THREAD

**Issue by asmagen** [GreenleafLab/ArchR#537]
Hello,

Say that I want to identify T cell populations in high resolution by ATAC seq, would you recommend using a two step approach with initial clustering, then filter to a new project and repeat the whole process again to ensure that the entire feature space is focused on the population of interest? Or would it be equally valuable (and easier/faster by eliminating one step) to just increase the sampling for iterative LSI and resolution in clustering to perform all of this task at once? How do you suggest exploring the impact of these options along with the resolution, sampleCells, n.start, varFeatures and dimsToUse parameters?

Note that I tried increasing the # of sampled cells to 25000 but the outputs suggest it's still using only 10000 cells:
2021-02-16 14:35:03 : Running LSI (3 of 4) on Variable Features, 10.291 mins elapsed.
###########
2021-02-16 14:35:03 : Sampling Cells (N = 10002) for Estimated LSI, 10.292 mins elapsed.

Thanks

**Comment by markphillippebworth** [comment]
Hey Asmagen,

I'm not a mod or a developer, but when I use ArchR, I've found that subsetting by major cell types does improve cell type labeling score, and helps get some better separation between subsets. I haven't turn to focus on getting clear separation of T cell populations yet, since they are so similar in gene expression (especially the naives). So far, it was a bit better, but I'd like to see improvement as well. 

Out of curiousity, when you set the # of sampled cells to 25000, did you change sampleCellsPre or did you change sampleCells within the clusterParams variable? 
(e.g. clusterParams = list(resolution = c(0.2), sampleCells = 10000, n.start = 10) ). 

If you do get better resolution by tweaking ArchR parameters, please share! This is something I'll need to return to as well, and it be interesting to see how you approach the question. I've been marking quality of cell type clusters by measuring the degree of mixture of cell type labels within a given cluster (Louvain or otherwise). My initial goal is to have 80% cell type label purity for a given cluster, though I'd like to move it higher.

**Comment by rcorces** [comment]
My intuition is the same as @markphillippebworth - I would first identify the subset of cells you are interested in and then re-perform dimensionality reduction and clustering just on that subset. I would expect that it would be hard/impossible for you to recapitulate the degree of difference from subclustering by merely adjusting parameters on the full dataset.

> How do you suggest exploring the impact of these options along with the resolution, sampleCells, n.start, varFeatures and dimsToUse parameters

I dont think I have systematic advice for this question that applies to all situations and data types beyond whats discussed in the manual. For the most part, these params aren't going to change too much but its worth exploring for your particular application

**Comment by asmagen** [comment]
Hi, thanks for your input. I adjusted the sampleCells within the clusterParams variable. Dows anybody have an idea of why it doesn’t work? And what’s sampleCellsPre?





On Feb 16, 2021, at 3:20 PM, markphillippebworth <notifications@github.com> wrote:






USE CAUTION: External Message.






Hey Asmagen,
I'm not a mod or a developer, but when I use ArchR, I've found that subsetting by major cell types does improve cell type labeling score, and helps get some better separation between subsets. I haven't turn to focus on getting clear separation of
 T cell populations yet, since they are so similar in gene expression (especially the naives). So far, it was a bit better, but I'd like to see improvement as well.
Out of curiousity, when you set the # of sampled cells to 25000, did you change sampleCellsPre or did you change sampleCells within the clusterParams variable?
(e.g. clusterParams = list(resolution = c(0.2), sampleCells = 10000, n.start = 10) ).
If you do get better resolution by tweaking ArchR parameters, please share! This is something I'll need to return to as well, and it be interesting to see how you approach the question. I've been marking quality of cell type clusters by measuring
 the degree of mixture of cell type labels within a given cluster (Louvain or otherwise). My initial goal is to have 80% cell type label purity for a given cluster, though I'd like to move it higher.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by rcorces** [comment]
@asmagen - you are tweaking an argument to `addClusters()` by passing `sampleCells` to `clusterParams` - https://www.archrproject.com/reference/addClusters.html

There is also the ability to sample cells for iterative LSI. https://www.archrproject.com/reference/addIterativeLSI.html

So when you say it isnt working, its just that you are tweaking the wrong thing.

Check out the parameter definitions above.

**Comment by asmagen** [comment]
Thanks
