### ISSUE TITLE
Confirm naming convention for motifs

### ISSUE THREAD

**Issue by gregszetoAI** [GreenleafLab/ArchR#544]
### If this is an issue with documentation that is absent/missing:

**Describe what material you feel should be explained**
As far as I can tell, the naming convention for motif features **MOTIF_### (###)** is not explained. 

Inferring from matrices and source, it looks like the trailing number after the **_** is the row number/idx from the PWM/peakAnnotation GRanges object, while the number in parentheses is the max mlog10padj for each TF in a deviation (I saw a `pMax != 100 ` logical in plotEnrichHeatmap)? If this is correct, would love to see a brief note added where useful in the docs and confirmation here. Thanks for such a great tool to the community!

**Where do you think this documentation would belong?**
Section 12 on motif enrichment

**Comment by jgranja24** [comment]
Hi @greenleaf-deploy-bot, the name refers to just the exact index from chromVARmotifs. This is a shorter name than the one in chromVAR for interpretability. Its mainly there to distinguish overlapping motif names if you use the V1 motifs. Yeah the number should be the max mlog10padj. The pMax 100 part just makes it so if you set pMax to 100 then it wont do that in parenthesis essentially. I would ignore that since its a sort of outdated feature! Hope that helps -Jeff

**Comment by NoemieL** [comment]
Hi. Sorry I am not sure I understand well the number in parentheses. In this example, is there a redundancy between the number in parentheses and the colour Norm. Enrichment -log10(P-adj)?

heatmapJASPAR<- plotEnrichHeatmap(enrichJASPAR, n = 10, transpose = TRUE)
[ATAC-Enriched-Marker-Heatmap_Translocation_Log2FC>=1_n10_rnareintegration.pdf](https://github.com/GreenleafLab/ArchR/files/7340352/ATAC-Enriched-Marker-Heatmap_Translocation_Log2FC.1_n10_rnareintegration.pdf)
