### ISSUE TITLE
 Identification of Positive TF-Regulators

### ISSUE THREAD

**Issue by NinaJiangL** [GreenleafLab/ArchR#550]
Hi, I am a bit confused regarding 15.4.
The example here is to analyze positive correlation of TF expression and motif across all cell groups. After I identified positive TF regulators from the correlation of motifMatrix and genescore , I got a list of potential regulators, but I am not sure how do I check back for the corresponding motif sequences from my ATAC data. How to pull the  specific motifs and its corresponiding sequences (logo) and location. (just like the motif prediction results like from Homer2）
![image](https://user-images.githubusercontent.com/18588687/109253782-782bdf00-782b-11eb-8865-57482a4ac294.png)
Also, I am confused about the lablels of the motif
e.g. CEBPA_185
what is the 185 stand for ?

Thanks

**Comment by rcorces** [comment]
We should add this to the documentation since it has come up in previous issues (#509).

Using the tutorial from Section 12.1 where we add motif annotations for cisbp
https://www.archrproject.com/bookdown/motif-enrichment-in-differential-peaks.html

```
PWMatrixToProbMatrix <- function(x){
	if (class(x) != "PWMatrix") stop("x must be a TFBSTools::PWMatrix object")
	m <- (exp(as(x, "matrix"))) * TFBSTools::bg(x)/sum(TFBSTools::bg(x))
	m <- t(t(m)/colSums(m))
	m
}
seqLogo(PWMatrixToProbMatrix(getPeakAnnotation(projHeme5, "Motif")$motifs[["SOX6_868"]]))
```

![image](https://user-images.githubusercontent.com/10343046/109258184-9c95a600-77ae-11eb-9db2-52f4d9479b14.png)


> Also, I am confused about the lablels of the motif
e.g. CEBPA_185
what is the 185 stand for ?

I believe the numbers are just unique identifiers that Jeff gave the motifs. But you can map them back to their chromVAR name using the `ID` column in the `motifSummary` attribute. The chromVAR motifs are described here:
https://github.com/GreenleafLab/chromVARmotifs

```
> getPeakAnnotation(projHeme5, "Motif")$motifSummary
DataFrame with 870 rows and 3 columns
                 name                                   ID      strand
          <character>                          <character> <character>
TFAP2B_1       TFAP2B    ENSG00000008196_LINE2_TFAP2B_D_N1           *
TFAP2D_2       TFAP2D       ENSG00000008197_LINE6_TFAP2D_D           *
TFAP2C_3       TFAP2C    ENSG00000087510_LINE7_TFAP2C_D_N3           *
TFAP2E_4       TFAP2E      ENSG00000116819_LINE19_TFAP2E_I           *
TFAP2A_5       TFAP2A   ENSG00000137203_LINE29_TFAP2A_D_N3           *
...               ...                                  ...         ...
SMAD5_866       SMAD5 ENSG00000113658_LINE19362_SMAD5_I_N1           *
SMAD9_867       SMAD9 ENSG00000120693_LINE19375_SMAD9_I_N1           *
SOX6_868         SOX6  ENSG00000110693_LINE19574_SOX6_I_N7           *
TBX18_869       TBX18 ENSG00000112837_LINE19949_TBX18_I_N1           *
TBX22_870       TBX22 ENSG00000122145_LINE20002_TBX22_I_N1           *
```
