### ISSUE TITLE
Batch effect assessment and corrections

### ISSUE THREAD

**Issue by asmagen** [GreenleafLab/ArchR#552]
How do you recommend to assess batch effects and their drivers in the various steps of the analysis, starting with the feature selection? Assuming I prefer to not force the batches on the same dimension with addHarmony, but rather detect with PC or feature set is driving that batch effect and removing it specifically from the clustering analysis of the joint batches, how can I find these features (and remove them) most efficiently?

Thank you

**Comment by rcorces** [comment]
We dont provide these types of recommendations because they are quite dependent on the given application. You might get better answers from a more general forum. In my personal opinion, there is a reason why the commonly used methods for batch correction have become commonly used - they tend to work for most applications. This is why we implemented Harmony because it is our recommended approach.
