### ISSUE TITLE
failed to rbind column 'seqnames' across DataFrame objects

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#553]
> proj4 <- addBgdPeaks(proj4)
Identifying Background Peaks!
Error in value[[3L]](cond) : 
  failed to rbind column 'seqnames' across DataFrame objects:
  could not find function ".validate_Vector_vertical_slots"

I realize that this a recurrent issue judging from the previous posts. However, is there any fix for it yet apart from reverting to an older version of R?

Thanks!

**Comment by rcorces** [comment]
Please use the provided issue templates.

Have you tried any of the suggestions in #271 ?

This appears to come from TFBS Tools. Since you dont provide a log file, I cant see which version of packages you are using. Try upgrading to R 4.0.3 if you arent there yet.
https://github.com/ge11232002/TFBSTools/issues/26

**Comment by sylestiel** [comment]
I was on R 4.0.3 when I encountered this problem. I just reverted to R v3.6.3. It is working now.

**Comment by rcorces** [comment]
Sorry for the hassle. We are working on a more stable way to distribute ArchR and all of its dependencies. The large number of dependencies is making it unstable across different computational setups and it is hard for us to diagnose these problems.
