### ISSUE TITLE
Peak2GeneLinks related question

### ISSUE THREAD

**Issue by sylestiel** [GreenleafLab/ArchR#554]
Can I forego running addPeak2GeneLinks() function for the 10X Multiomic assay?

> proj5 <- addPeak2GeneLinks(
+     ArchRProj = proj5,
+     useMatrix = "GeneExpressionMatrix",
+     reducedDims = "LSI_Combined"
+ )
ArchR logging to : ArchRLogs/ArchR-addPeak2GeneLinks-104ea586820dc-Date-2021-02-26_Time-13-40-48.log
If there is an issue, please report to github with logFile!
2021-02-26 13:40:48 : Getting Available Matrices, 0.001 mins elapsed.
**Error in h5read(ArrowFiles[x], paste0(useMatrix, "/Info/predictionScore")) : 
  Object 'GeneExpressionMatrix/Info/predictionScore' does not exist in this HDF5 file.**
[ArchR-addPeak2GeneLinks-104ea586820dc-Date-2021-02-26_Time-13-40-48.log](https://github.com/GreenleafLab/ArchR/files/6052036/ArchR-addPeak2GeneLinks-104ea586820dc-Date-2021-02-26_Time-13-40-48.log)

**Comment by sylestiel** [comment]
Addressed it!

**Comment by sylestiel** [comment]
Cannot get it to plot the links!  So need some input.

**Comment by rcorces** [comment]
Please use the issue templates when posting issues. This ensures that you provide us with the information that we need to help you.

I dont have enought information to answer your question.

**Comment by sylestiel** [comment]
I did use the issue template (documentation). What am I missing?  I don't understand what you mean when you say I must use an issue template. Also I did provide a log to help with the problem encountered. At times I cannot quite categorize the problem faced  because I cannot  tell if it is a bug in the program or something that I'm entering incorrectly. Please tell me what information i can provide so that you may be able to locate the nature of the problem.

**Comment by rcorces** [comment]
When you start a new issue, you are provided an issue template, shown below. This template asks specific questions that are geared to help us help you. In order to post this issue, you would have had to delete all of that text.
![image](https://user-images.githubusercontent.com/10343046/109397422-5134e200-78eb-11eb-8bf0-20115ff4eefa.png)

You issue should look like this:

**Describe what material you feel should be explained**
A concise and clear explanation of what documentation could be improved

**Where do you think this documentation would belong?**
For example: This would belong in Section 4.3 of the user manual.
OR
You should create a new section in the user manual in Chapter 4.

When asking a question like "Can I forego running addPeak2GeneLinks() function for the 10X Multiomic assay?" a simple response would be "depends on your application" which isnt helpful for you. Of course you dont have to run `addPeak2GeneLinks()` if you dont care about peak to gene links.

**Comment by sylestiel** [comment]
Thanks for explaining it to me.

I'm trying to run the ArchR full manual on a multiomic assay. I did use  the html provided but wanted to continue further along with all the downstream analyses provided in the original full manual. I was trying to applying the first script in chapter 15.3 entitled Peaks2GeneLinkage in ArchR 
projHeme5 <- addPeak2GeneLinks(
    ArchRProj = projHeme5,
    reducedDims = "IterativeLSI"
)

by changing the reducedDims to Combined_LSI.

I tried to change the useMatrix to "GeneExpressionMatrix" as opposed to GeneIntergrationMatrix but the program is looking for Predicted I.d. which is not applicable to the Mulitomic assay,
Hence the Error message I imagine. Looking for ways to circumvent this error to generating P2G links in the Multiomic Assay.

Thanks!

**Comment by rcorces** [comment]
Thank you! That is much more helpful!

I believe that this was fixed in a recent commit (https://github.com/GreenleafLab/ArchR/commit/ecfe12a6b4df80beec1bf16be3b398433a7742bd)

Can you update to the latest release of v1.0.1. I know you are already on 1.0.1 but must not be the official release. You should be able to do that with:

`devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())`

In the most recent version, this error should be caught and ignored.
https://github.com/GreenleafLab/ArchR/blob/ecfe12a6b4df80beec1bf16be3b398433a7742bd/R/IntegrativeAnalysis.R#L1032

Please close if this solves your issue.

**Comment by sylestiel** [comment]
That fixed it! Thanks!
