### ISSUE TITLE
different sizes peak2gene

### ISSUE THREAD

**Issue by rojinsafavi** [GreenleafLab/ArchR#559]
I am not sure if this is a bug or not, but the number of rows is different. if it's not a bug, would you please explain why it is different?

<img width="550" alt="Screen Shot 2021-03-01 at 3 22 25 PM" src="https://user-images.githubusercontent.com/19545198/109572482-1f19b080-7aa2-11eb-98a5-e3bb47180d4e.png">

**Comment by rcorces** [comment]
I can recapitulate this behavior with the tutorial data as well though I'm not sure it is a bug. My assumption is that the difference is due to the use of `unique()` on the loops object here:
https://github.com/GreenleafLab/ArchR/blob/ecfe12a6b4df80beec1bf16be3b398433a7742bd/R/IntegrativeAnalysis.R#L1337

So there could be multiple loops from the same peak to the same promoter region (marked by multiple genes) and these get removed because they are effectively the same for the purposes of displaying loops in the browser track.

**Comment by rcorces** [comment]
Worth mentioning that prior to `unique()` the loops are ordered in such a way that (I think) the strongest loop is kept for display.
