### ISSUE TITLE
Cairo required by ComplexHeatmap

### ISSUE THREAD

**Issue by ChangliangWang** [GreenleafLab/ArchR#561]
Dear ArchR maintainers,

As I didn't install 'Cairo' successfully, when I use devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories()) to install ArchR, it will skip the installation because of no available 'Cairo'. Could I install ArchR 1.0.1 without 'Cairo'?

Best wishes,
Changliang.

**Comment by rcorces** [comment]
Hi @ChangliangWang - That doesnt sound right to me. ArchR installation should not depend on Cairo. Can you post whatever error message you are getting with the installation?

**Comment by ChangliangWang** [comment]
The detailed error information as below:

ERROR: configuration failed for package ‘Cairo’
* removing ‘/share/home/wangchangliang/miniconda3/envs/archR/lib/R/library/Cairo’
Error: Failed to install 'ArchR' from GitHub:
  (converted from warning) installation of package ‘Cairo’ had non-zero exit status

Best wishes,
Changliang.

________________________________
发件人: Ryan Corces <notifications@github.com>
发送时间: 2021年3月2日 23:21
收件人: GreenleafLab/ArchR <ArchR@noreply.github.com>
抄送: Wang Changliang <yb67610@connect.um.edu.mo>; Mention <mention@noreply.github.com>
主题: Re: [GreenleafLab/ArchR] Install ArchR 1.0.1 (#561)


Hi @ChangliangWang<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ChangliangWang&d=DwMCaQ&c=KXXihdR8fRNGFkKiMQzstu-8MbOxd1NuZkcSBymGmgo&r=bhPcwygvMRH7vWVpUUxVrQ&m=Ioih6yINJyYrDLNNUDRX40lp0e7q06xFUkUC3fKeVEk&s=MewDPWjkzQlK0FMURk5hTFxc9qlZ0tBbB6ggcZfdKDk&e=> - That doesnt sound right to me. ArchR installation should not depend on Cairo. Can you post whatever error message you are getting with the installation?

―

**Comment by Kaivalyamolugu** [comment]
I have had the same issue too which got resolved after installing Cairo. 

Best, 
Kaivalya

**Comment by rcorces** [comment]
Thanks for reporting this. We will look into it.

**Comment by smorabit** [comment]
I just wanted to chime in and say that running this:

`devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.1", repos = BiocManager::repositories())`

using `ref=` `master`, `release_1.0.0`, `release_1.0.1`, and `release_1.0.2` all failed at the same step when trying to install Cairo. I have previously installed ArchR 1.0.0 without Cairo and it didn't give me this error.

**Comment by rcorces** [comment]
Maybe one of ArchR's dependencies started depending on Cairo in a new version? From what I can tell, ArchR definitely does not explicitly depend on Cairo. When does it try to install Cairo? Is it clear whether Cairo is being pulled in for installation because of some other package?

**Comment by smorabit** [comment]
I am just even more confused now, but I tried to install ArchR again using the master branch to check at what point Cairo was being installed, and this time it was somehow able to install. Sometimes R makes me think I am going insane, lol. Just from looking at the console during the installation I saw that it started installing Cairo right after motifmatchr was downloaded.

**Comment by skywalker51616** [comment]
same error: 

configure: error: Cannot use cairo-ft backend, although cairo claims it is working. Please check your caito installation and/or update cairo if necessary or set CAIRO_CFLAGS/CAIRO_LIBS accordingly.
ERROR: configuration failed for package ‘Cairo’

**Comment by skywalker51616** [comment]
One solution is: 

conda install -c conda-forge r-cairo

**Comment by rcorces** [comment]
It looks to me like the latest versions of `ComplexHeatmap` now import `Cairo` whereas before it was suggested. So you are getting this error because ArchR imports `ComplexHeatmap` which has recently changed to import `Cairo`. 
This went into effect in Oct 2020 via this commit in ComplexHeatmap - https://github.com/jokergoo/ComplexHeatmap/commit/ae913eddca0ed8f4ad476e052218830124387093

We do not currently have a way around this but will work on something. In the meantime, you will need to install Cairo. Cairo is [a system library](https://www.cairographics.org/) AND [an R package](https://cran.rstudio.com/web/packages/Cairo/index.html). You cannot install the R package until the system library is properly installed. If you have sudo/admin privs installing the system library should be easy. If you do not, then you could ask your sys admin to install it or you could use conda as suggested by @skywalker51616 though we dont use conda and there have been some anecdotal reports of problems with conda and ArchR.

**Comment by rcorces** [comment]
Closing. This appears to no longer be an issue. ComplexHeatmap has returned to "suggest" for Cairo.
