### ISSUE TITLE
Error in ArchRProject

### ISSUE THREAD

**Issue by tianchen2019** [GreenleafLab/ArchR#603]
**Attach your log file**
[ArchR-createArrows-2297bbfbc3ce-Date-2021-03-08_Time-15-58-25.log](https://github.com/GreenleafLab/ArchR/files/6099870/ArchR-createArrows-2297bbfbc3ce-Date-2021-03-08_Time-15-58-25.log)

**Describe the bug**
when i use your tutorial hematopoiesis dataset,the program stops automatically in ArchRProject.
the code is 
```
library(ArchR)
inputFiles <- getTutorialData("Hematopoiesis")
addArchRGenome("hg19")
addArchRThreads(threads = 20)
ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000,
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)
ArrowFiles
proj <- ArchRProject(
  ArrowFiles = ArrowFiles,
  outputDirectory = "HemeTutorial",
  copyArrows = TRUE #This is recommened so that you maintain an unaltered copy for later usage.
)
```
the log file is 
```
2021-03-08 16:01:41 : (scATAC_CD34_BMMC_R1 : 2 of 3) Adding GeneScoreMatrix!, 3.274 mins elapsed.
2021-03-08 16:01:48 : (scATAC_PBMC_R1 : 3 of 3) Adding GeneScoreMatrix!, 3.384 mins elapsed.
2021-03-08 16:02:14 : (scATAC_BMMC_R1 : 1 of 3) Adding GeneScoreMatrix!, 3.821 mins elapsed.
2021-03-08 16:02:21 : (scATAC_CD34_BMMC_R1 : 2 of 3) Finished Creating Arrow File, 3.929 mins elapsed.
2021-03-08 16:02:34 : (scATAC_PBMC_R1 : 3 of 3) Finished Creating Arrow File, 4.149 mins elapsed.
2021-03-08 16:02:55 : (scATAC_BMMC_R1 : 1 of 3) Finished Creating Arrow File, 4.495 mins elapsed.
ArchR logging successful to : ArchRLogs/ArchR-createArrows-2297bbfbc3ce-Date-2021-03-08_Time-15-58-25.log
[1] "scATAC_BMMC_R1.arrow"      "scATAC_CD34_BMMC_R1.arrow"
[3] "scATAC_PBMC_R1.arrow"
Using GeneAnnotation set by addArchRGenome(Hg19)!
Using GeneAnnotation set by addArchRGenome(Hg19)!
Validating Arrows...
```
The program seems to stop in Validating Arrows. And the output file HemeTutorial is empty. There is 8.7T of storage left.

**Comment by rcorces** [comment]
Sorry you are having trouble with running the tutorial. Unfortunately, I am not sure how to help. Creation of Arrow files for the tutorial could take ~10 minutes. Many users have run this tutorial code on the tutorial data across a wide array of computational environments. If you are having trouble, I'd suggest trying a different compute environment in case that is something odd about the one you are using.

**Comment by tianchen2019** [comment]
> Sorry you are having trouble with running the tutorial. Unfortunately, I am not sure how to help. Creation of Arrow files for the tutorial could take ~10 minutes. Many users have run this tutorial code on the tutorial data across a wide array of computational environments. If you are having trouble, I'd suggest trying a different compute environment in case that is something odd about the one you are using.

After trying, this error has now appeared in this step.
```
Using GeneAnnotation set by addArchRGenome(Mm10)!
Using GeneAnnotation set by addArchRGenome(Mm10)!
Validating Arrows...
Error in H5Fopen(file, "H5F_ACC_RDONLY", native = native) :
  HDF5. File accessibilty. Unable to open file.
```

**Comment by tianchen2019** [comment]
> From your last post, it looks like you are not running the tutorial code on the tutorial data (you are in mm10). Please run the tutorial code on the tutorial data and report back.
I found the same error in issues section and solved it with his solution by seting environment variable RHDF5_USE_FILE_LOCKING=FALSE.
https://github.com/GreenleafLab/ArchR/issues/248#issuecomment-789453997

**Comment by rcorces** [comment]
Glad this worked for you. Closing this issue.

**Comment by IqRaZaFaR16** [comment]
Hello sorry for disturbing you again i have installed ArchR version 1.0.3 and also change my seurat and seuratobject verson but encountry file while 

Merged.proj2 <- addArchRAnnotations(ArchRProj = Merged.proj2, db = "LOLA",collection = "EncodeTFBS")
even i have installed library(LOLA) also unable multthreadng while creating arrow files
i have try this for both mm10 and toturial hg19 but still get the same error related to enable to rhdf5 file open Merged.proj2  <- addArchRAnnotations(ArchRProj = Merged.proj2, db = "LOLA", collection = "EncodeTFBS")
ArchR logging to : ArchRLogs/ArchR-addArchRAnnotations-1aaf5561d22cf4-Date-2024-12-05_Time-15-38-16.670967.log
If there is an issue, please report to github with logFile!
Error in H5Fopen(file, flags = flags, fapl = fapl, native = native) :
  HDF5. File accessibility. Unable to open file.
>
even i have disable multithreading and also install ArchR via using dev still have this issue is there anyone who guide me to fic this problem
Please guide me how i can fix it.
