### ISSUE TITLE
issue on installation: fatal error:boost/detail/fenv.hpp: no such file or directory #bug

### ISSUE THREAD

**Issue by xinmiaoyan** [GreenleafLab/ArchR#708]
when I install ArchR on my HPC-linux account under R, a fatal error (boost/detail/fenv.hpp: no such file or directory)occurred, in fact the boost/detail/fenv.hpp does exist. I googled and didn't find solution. Enclosed is the detail.
Did you encounter such problems? if yes, how do you solve this issue. I really appreciate your response.

![Screen Shot 2021-04-22 at 2 51 22 PM](https://user-images.githubusercontent.com/83053884/115819040-b117a880-a3c3-11eb-9fb4-4e713cbe3ba0.png)

**Comment by rcorces** [comment]
Thanks for using ArchR.
This is not an installation problem with ArchR but rather with `RSQLite`. I would recommend contacting your HPC system administrator for help getting this package to install. This error has not been reported previously and is likely unique to your system. The root cause is not something that we can help you troubleshoot.

**Comment by xinmiaoyan** [comment]
thanks for your suggestions. have a good day.

Ryan Corces ***@***.***> 于2021年4月23日周五 上午9:20写道：
