### ISSUE TITLE
unable to do use correlateMatrices fuction

### ISSUE THREAD

**Issue by dandata123-tech** [GreenleafLab/ArchR#829]
Hi,Greenleaf
Your work is really good and kind to green hand.
but i met some trouble in correlateMatrices.
My data is mouse ATAC,when I subset the cluster I want, I use MAC2 and homer to do the peak call and motif enrichment and findMarker between the Sample
But when i use the CorrelateMatrices function,
The Archr said there is no relattionship between the two matrix.
if it is my data promblem or something I miss 
and here is my log file.
[ArchR-correlateMatrices-e52725368d0e-Date-2021-06-17_Time-23-08-23.log](https://github.com/GreenleafLab/ArchR/files/6680785/ArchR-correlateMatrices-e52725368d0e-Date-2021-06-17_Time-23-08-23.log)

and i also meet some trouble when i use footsprint
and here is the log
[ArchR-plotFootprints-e527690bba84-Date-2021-06-17_Time-22-16-24.log](https://github.com/GreenleafLab/ArchR/files/6680787/ArchR-plotFootprints-e527690bba84-Date-2021-06-17_Time-22-16-24.log)

I am looking foward to your reply and it will means a lot for me.
thx

Yours ,
Dan

**Comment by rcorces** [comment]
Please only post one error per issue.

Your problem with `correlateMatrices()` is that there are no mappings between your two matrices. This is because none of the features in the `matchName` columns (visible in your log file) match between your `GeneScoreMatrix` and your `Homer_MotifMatrix`. If you want to correlate these matrices, they must have matching features.

You can open a new issue for your footprinting problems but your log file has no error.

**Comment by dandata123-tech** [comment]
Thank you for replying me.Is that ok for the outcome which don’t have matching features?or I miss something important step?
