### ISSUE TITLE
Creating Arrow files with tutorial data 

### ISSUE THREAD

**Issue by ozturan** [GreenleafLab/ArchR#92]
Hi,

Just downloaded ArchR and tried to use the tutorial data. I've set the thread to 1 (just in case) and give it a go. I'm getting this error.

Thank you

[ArchR-createArrows-4ca794f406c-Date-2020-05-02_Time-01-59-00.log](https://github.com/GreenleafLab/ArchR/files/4566592/ArchR-createArrows-4ca794f406c-Date-2020-05-02_Time-01-59-00.log)

**Comment by rcorces** [comment]
This is very likely an error with ggrastr and Cairo. We just pushed an update just a few minutes ago which will let you get around this error but we do recommend getting Cairo installed properly because this is how ArchR rasterizes plots.

First, I would recommend re-installing ArchR using the install instructions on www.ArchRProject.com

Then, you should be able to check if Cairo is working properly with
`Cairo::Cairo(type='raster'); dev.off()`

**Comment by ozturan** [comment]
Thank you, it worked. I had to install X11 on my mac to properly install Cairo.

**Comment by jgranja24** [comment]
Great to hear closing the issue. Feel free to open if you have more issues.
