### ISSUE TITLE
No fragments found

### ISSUE THREAD

**Issue by ozturan** [GreenleafLab/ArchR#93]
Hi,

I used my own 10X inputs to ArchR and somehow I couldn't create the arrow file. 

I also tried to extract the 10x barcodes with `getValidBarcodes()` and feed it into the `createArrowFiles()` function. It did not work. Also tried to add 'chr' string to each line in the fragments file. It did not work either. 

This .log file is the attempt with 10x fragments file as it is. 

Thank you. 

[ArchR-createArrows-4456fb7160a-Date-2020-05-02_Time-04-33-16.log](https://github.com/GreenleafLab/ArchR/files/4566875/ArchR-createArrows-4456fb7160a-Date-2020-05-02_Time-04-33-16.log)

**Comment by jgranja24** [comment]
Can you show the top few lines from the fragments file? There is also a 
function `reformatFragmentFiles` to fix problematic fragment files.

**Comment by ozturan** [comment]
`1	10073	10558	CCCACATAGCAACGGT-1	1
1	10079	10322	TCAAGGTGTCTCTGGG-1	1
1	10079	10487	GCGAGAAGTGAATCGG-1	1
1	10079	10569	TGATTTCCAAAGCTGG-1	1
1	10083	10338	GCGATTATCGATAGGG-1	1`

Here it is.

**Comment by rcorces** [comment]
I believe this is an issue with the chromosome names in your fragment file. ArchR expects the `seqnames`/chromosome names to start with "chr". This is a check that is put in place to protect users from doing something unexpected. I will make this more clear in the user manual.

See issue #88  for a detailed description of the problem, how to fix it, etc. You will likely need to update ArchR to the latest version 0.9.3 which was released 5/1/20 in the afternoon.

Let us know if this fixes your problem and feel free to close the issue if it does.

**Comment by rcorces** [comment]
@jgranja24 - apparently this did not solve the problem Perhaps i misinterpreted the issue. any suggestions?

**Comment by jgranja24** [comment]
This is not the same issue as #88 because there they have a non model genome. This is a formatting issue since you are trying to work with hg19. My suggestion is to try what I suggested previously.

(1) Since your fragment files do not have a "chr", please paste this to the first column. hg19 is a model genome and chromosomes (with the exception of snp formatting) are almost always referred to as chr1, chr2 etc. ArchR would have no way of knowing this based on your input.

(2) Run `reformatFragmentFiles` on these files to make sure they are properly tabix setup.

(3) Re-run `createArrowFiles`.

If this still does not work feel free to add additional comments.

**Comment by ozturan** [comment]
That was only thing that I haven't tried. I've tried and it worked. Given the fact that the majority of the users will be using 10X inputs, I would suggest to write these feedbacks in the manual for future users. 

Most of the people would want to use their 10X inputs directly in ArchR. This would be a good heads up for them.

Thank you!

**Comment by jgranja24** [comment]
Awesome! Yeah we will add some info for additional users. Thanks for your patience.

**Comment by rcorces** [comment]
> Given the fact that the majority of the users will be using 10X inputs, I would suggest to write these feedbacks in the manual for future users.

Sorry - just want to clarify this for other users that might see this issue - ArchR is fully capable of handling fragment files from CellRanger directly and this is, in fact, the best type of input for ArchR. I believe the problem here is that your reference genome does not have "chr" prefixes on the chromosomes. So when you did the alignment, your fragment files did not get "chr" prefixes on the chromosomes. Is that true?

Most users, especially those using the default reference genome from the 10x website, will not encounter this issue.

That being said, I will add additional info to the documentation about the expectation of "chr" prefixes.

Thanks for your help addressing this issue!

**Comment by ozturan** [comment]
Yeah that's the case. That's why I couldn't use the file as an input to ArchR. 

We actually used the 10X website. I believe it's better to fix the newly updated `addArchRChrPrefix()` function and people would have no problem. I would guarantee that people would have inputs like I had (without a "chr" prefix) and will have problems. 

> That being said, I will add additional info to the documentation about the expectation of "chr" prefixes.
That's great!

Thank you for the quick responses!

**Comment by jgranja24** [comment]
> I believe it's better to fix the newly updated addArchRChrPrefix() function and people would have no problem. 

This option is not meant for your case. It is meant to disable chr prefix but it still requires **exact** matching of chromosome. Ie your annotations must also be **exactly** the same.

This is a lot harder said than done. ArchR uses a sophisticated method for parsing a fragments file. 

>  I would guarantee that people would have inputs like I had (without a "chr" prefix) and will have problems.

This isnt a fragments file by definition. I understand the difficulties but there is a method to the madness.

We will update `reformatFragmentFiles` to make this much easier for users.

**Comment by ozturan** [comment]
> This isnt a fragments file by definition. I understand the difficulties but there is a method to the madness.

This is a fragments file that I got directly from 10X, so it's a fragments file and people would want to use it directly. If you could explicitly state that users need properly-tabbed input with a "chr" prefix, I'm sure that would have solved the problem here. 

Thank you!

**Comment by jgranja24** [comment]
Okay ill look into it more. 

Good luck with your analysis adventures.
