### ISSUE TITLE
scRNA-seq and scATAC-seq integration

### ISSUE THREAD

**Issue by doncarlos999** [GreenleafLab/ArchR#94]
Great package and superb documentation.

Maybe I missed it in the documentation but is it possible to plot integrated scRNA-seq and scATAC-seq on the same UMAP? 
As in the examples here https://satijalab.org/signac/articles/integration.html

If not, and again sorry if I missed it in the documentation, is it possible to export an arrow project to a SingleCellExperiment or Seurat class object?

Thanks

**Comment by rcorces** [comment]
I'm not sure that I completely understand the use case. I'll try to clarify a bit whats going on during integration.

When you "integrate" scATAC-seq with scRNA-seq, you are actually assigning gene expression values to the scATAC-seq cells. So each individual cell from the scATAC-seq project now has gene expression values associated with it. It sounds like your interpretation was that you create a merged dataset with cells from scATAC-seq and cells from scRNA-seq together in the same dataset. This is not what happens.

Given that, its not really possible to plot scATAC-seq and scRNA-seq on the same UMAP plot because they are two attributes of the same single cells. You can, of course, overlay attributes like gene expression or gene score by color on two separate plots of the same UMAP embedding but I dont believe thats what you are asking.

I'd recommend reading through the relevant documentation section if this isnt clear. starting here:
https://www.archrproject.com/bookdown/defining-cluster-identity-with-scrna-seq.html

To answer your second question - no it is not currently possible to export an Arrow file or ArchRProject object to a SingleCellExperiment object or Seurat class object. Do you have a particular use case for either of those?

If I've misunderstood your question, feel free to follow up, preferably by using the issue template system that we set up.

**Comment by doncarlos999** [comment]
Thanks for the fast response. 

**Describe the problem that your feature request would address.**
I would like to recreate this kind of plot:
<img width="80" alt="scATAC-scRNA-seq" src="https://user-images.githubusercontent.com/29129699/80857512-5e5e5180-8c85-11ea-8497-e9acb3c02b02.png">
Here single cells were extracted from the same tissue but half were used for scRNA-seq and the other half for scATAC-seq.

**Describe the solution you'd like**
Plotting separate single cells from scRNA-seq and scATAC-seq on the same UMAP.
If not possible then a way to export ArchR project to Seurat or SingleCellExperiment so that I can combine the data there.

**Describe alternatives you've considered**


**Additional context**
From your description of how ArchR integration works and additional reading in the documentation I understand that it is just adding the expression data as another attribute for the ATAC-cells. What I am trying to do is slightly different.

**Comment by jgranja24** [comment]
I understand what you want here, but there are a few challenges to get this desired output. ArchR's integration framework (using Seurat) efficiently blocks the job into small numbers of cells and then will store the results in the Arrow Files / ArchRProject. Because this is done in smaller increments it makes less sense to make a UMAP/TSNE of the aligned cca subspace in these chunks. 

The best we can do here is add an option to save the CCA subspace for all blocks in a folder within the `outputDirectory` of the ArchRProject. Then you could load this into R and create a UMAP for this. You can also increase the blocking size (`sampleCellsATAC` and `sampleCellsRNA`) to make it 1 integration block. However, you may experience decrease in efficiency.

The reason ArchR is designed this way is because we find the most practical use of scRNA is the integrative analyses (peak to gene linkage and positive TF regulators) we implemented rather than making a joint UMAP.

**Comment by doncarlos999** [comment]
> The best we can do here is add an option to save the CCA subspace for all blocks in a folder within the outputDirectory of the ArchRProject. Then you could load this into R and create a UMAP for this. You can also increase the blocking size (sampleCellsATAC and sampleCellsRNA) to make it 1 integration block. However, you may experience decrease in efficiency.
This would be super useful if it isn't too much work to implement it.

> The reason ArchR is designed this way is because we find the most practical use of scRNA is the integrative analyses (peak to gene linkage and positive TF regulators) we implemented rather than making a joint UMAP.
This makes perfect sense and I have found the gene linkage and positive TF regulator analysis tools to be really useful!

I just like the idea of being able to show how closely the scRNA-seq and scATAC-seq cells are matching before integrating the expression onto the scATAC cells.

**Comment by rcorces** [comment]
> I just like the idea of being able to show how closely the scRNA-seq and scATAC-seq cells are matching before integrating the expression onto the scATAC cells.

This use case makes total sense to me and I think we should minimally support some metric to assess how well the RNA and ATAC match during the integration process. It would be ideal if this were possible without using 1 integration block as every user should be able to assess the goodness of the integration.

@jgranja24 - shouldnt you be able to do this on a per-chunk basis? For ex. an option that creates the desired UMAP plot for the first chunk (or all chunks) during integration?

**Comment by jgranja24** [comment]
I can add something like this, but it will take some time to make sure it doesnt cause further issues.

**Comment by jgranja24** [comment]
I just added in the dev branch what you are looking for. It will now plot a joint UMAP of the ATAC and the RNA from the CCA analysis. Please let me know if you have further issues.  To install the dev branch feel free to use

`
devtools::install_github(
"GreenleafLab/ArchR",
ref="dev_050120",
repos = BiocManager::repositories()
)
`

We will commit to master these changes in a day or so.

**Comment by jgranja24** [comment]
<img width="808" alt="Screen Shot 2020-05-04 at 5 43 22 PM" src="https://user-images.githubusercontent.com/25017655/81039965-27dc2e80-8e5f-11ea-8603-3cfd457c9baa.png">

This is an example of the output you will receive in the RNAIntegration subdirectory for each integration block. Also it'll save an RDS with the UMAP, CCA and cell info.

**Comment by doncarlos999** [comment]
This is exactly the kind of plot I was hoping to generate. Thanks a lot.

**Comment by CSBioAzim** [comment]
@jgranja24, This sounds cool. Would it be possible also to plot the colustering of scRNA-seq and scATAC in two different plot as well? Now it's superimposed.

**Comment by jindalk** [comment]
> The best we can do here is add an option to save the CCA subspace for all blocks in a folder within the `outputDirectory` of the ArchRProject.

Curious to know if you've implemented this functionality as well in the dev branch? Thanks so much for adding this joint UMAP btw, it seems to be very helpful!
