### ISSUE TITLE
How to do differential (integrative) anlysis between case and control ?

### ISSUE THREAD

**Issue by CSBioAzim** [GreenleafLab/ArchR#96]
Hi,

Great package, but I think one important aspect of the analysis is missing in your package.
I would love to have the following feature in your package.
Given that fact most of the time people have single-cell data from case and control groups, and they are interested to learn about disease-specific perturbation in a cell type-specific manner.
For example, linking differential peaks (between disease-control) to differential gene expression. or
Looking for differential TF activity in a specific cell type between case and control.

Having these features can increase the use case of your package.

**Comment by rcorces** [comment]
Pairwise differential testing is already a feature of ArchR. A quick search of the manual would have turned this up as shown in the below screenshot.
![image](https://user-images.githubusercontent.com/10343046/80869369-eb3ce700-8c54-11ea-9246-16918f653d8b.png)

https://www.archrproject.com/bookdown/pairwise-testing-between-groups.html

**Comment by CSBioAzim** [comment]
@rcorces, I know this, but this section does only differential analysis between cell types.
What do I mean is that doing differential analysis for cell type A between condition 1 and condition 2.
Also, if I have samples from two categories (condition A, B), do I need to do peak calling combined or I should do it separately?

**Comment by rcorces** [comment]
The linked section of the documentation discusses "cell groups" rather than "cell types" and uses a curated cell group called "Clusters2". The user defines the cell groups. Defining cell groups is outlined here under example 3:
https://www.archrproject.com/bookdown/manipulating-an-archrproject.html

You need to define a cell group that works for your application. This will become a new column in `cellColData` that is passed to `useGroups` or `bgdGroups`. To be explicitly clear, your new cell group would be something like "condition-cellType" and you would compare "condition1-CellTypeA" to "condition2-CellTypeA".

In terms of your question about peak calling, this is an application-specific question that we cant possibly answer with any confidence, though my intuition would be to use the default reproducible peak set defined by ArchR.

While I appreciate that the documentation is quite extensive and would take some time to read thoroughly, we (the developers) will struggle to answer application-specific questions. I will update the relevant documentation section to make it explicitly clear that the cell groups can be user defined but I do believe this would be clear after an in-depth read of the user manual.
